[[tests]]
input = '''
4 8
........
........
..####..
........
'''
output = '''
........
...##...
...##...
...##...
'''

[[tests]]
input = '''
4 8
......#.
.##...#.
.#.#..#.
..#.....
'''
output = '''
........
.##..###
.#.#....
..#.....
'''

[[tests]]
input = '''
7 18
..................
.###..............
.#................
..#.............#.
..............#.#.
.....##........##.
.....##...........
'''
output = '''
..#...............
.##...............
.#.#..............
...............#..
................##
.....##........##.
.....##...........
'''

[[tests]]
input = '''
7 16
.......##.......
.......##.......
.#..#......#....
#........#...#..
#...#......####.
####......#.....
................
'''
output = '''
.......##.......
.......##.......
........#.......
##........##.##.
#.##......#####.
####.......###..
.##.............
'''

[[tests]]
input = '''
17 16
..#.##.###.#...#
.#.#####.##..###
####..###.######
.##....####..#.#
.#####..####..##
.####.#.#.#....#
#.###.#....#.###
#.#..#.#...#..#.
..#########.##..
.#..#.##.###...#
##.#.#.#.#.#####
..###.#..####...
##.####.##..##.#
.#.#.##..###.##.
#....###.#.###.#
#.#..#.#...#####
.##..#####.#....
'''
output = '''
..#....#.#.....#
#...............
#...............
.....#..........
#....##....#...#
#.....#.#...##..
#.....#...####.#
.........#.#...#
..#.........###.
##.............#
##.....#.....###
...............#
##......#.......
.#.#...........#
#.#....#.#.....#
#.#.#....#.....#
.##..#.##.##.##.
'''

[[tests]]
input = '''
6 5
#####
#####
.####
.#.##
#..##
###.#
'''
output = '''
#...#
.....
.....
##...
#....
###.#
'''

[[tests]]
input = '''
3 12
..#.........
.....#......
...........#
'''
output = '''
............
............
............
'''

[[tests]]
input = '''
2 11
######..#.#
##...#.#..#
'''
output = '''
#.#####..#.
#..#.##..#.
'''

[[tests]]
input = '''
17 8
.##.####
####..##
..##.###
..######
####.###
##...###
#.######
########
########
#.##.#.#
#.####.#
#.#.####
#####..#
###.###.
..######
.#.#####
.######.
'''
output = '''
#...##.#
#.......
........
........
#.......
........
........
........
........
#......#
#......#
#......#
.......#
#.......
#.......
.#......
.#.....#
'''

[[tests]]
input = '''
5 3
###
##.
###
###
###
'''
output = '''
#.#
...
...
...
#.#
'''

[[tests]]
input = '''
13 14
#####.##.#..##
###########.##
##.#####..##.#
#####..#####.#
##.###..####.#
.##.#..##.###.
####..#######.
.##..####.#.##
##.#####.#####
##..###.######
###.#..#######
####..##..##.#
#.#.###.######
'''
output = '''
#........#####
..............
.............#
.............#
.....##......#
.............#
#...#.........
..............
...#..........
..............
....#.........
..............
#.#.###.##...#
'''

[[tests]]
input = '''
8 13
..####.#.##.#
############.
####....#.###
.##.######.#.
.##..####.##.
###.#.##..#.#
..########.##
.##..#..#.#..
'''
output = '''
.......#.....
#............
............#
....#........
............#
#...........#
#...........#
.##..#..#.##.
'''

[[tests]]
input = '''
20 12
............
............
#.........#.
..#.........
............
#.........#.
.....#......
............
...#....#..#
...........#
.#..........
#...........
............
.........#..
......#.....
...........#
....#.......
#.......#...
............
............
'''
output = '''
............
............
............
............
............
............
............
............
............
............
............
............
............
............
............
............
............
............
............
............
'''

[[tests]]
input = '''
8 13
#..#..#...#..
....#.....#..
.............
..#..........
#....#....#..
.............
....#...#.#..
....#........
'''
output = '''
.............
.............
.............
.............
.............
.........#...
.............
.............
'''

[[tests]]
input = '''
7 15
#.#.........###
....##.#...#..#
.#....##.....#.
.##.#...#..#.#.
........##....#
#.###........##
...#..#........
'''
output = '''
............###
.#...#.#......#
.####.###....##
.##.....##..###
....#...##..#.#
..###........##
..###..........
'''

[[tests]]
input = '''
16 20
##.###.####.##...#.#
##.##.#.#####.#.###.
###..##.#.....##.#.#
..###.###.#.#...#..#
.#.##.#.#.##.....#.#
...###.##.#...#....#
####.#..#....#.#.###
.#..####...###..###.
....#..#..#.#..###.#
##.####..###########
#############.....#.
...#####....###.#.##
.##.####.###.###.##.
...#####..#..#.#####
.#####.###...#..###.
.#.#..#.###...#.##.#
'''
output = '''
##.#.###....##..##..
............#.#....#
#...........#.#....#
#.......#.#....###.#
..........#........#
#.......#.##..#.##.#
##......##.#.#.#...#
##.....##..#.#......
###....###.........#
#.............#....#
#...................
#...............#..#
..#......###........
...........#.#.....#
.#...........#......
.#.#.##...#....##...
'''

[[tests]]
input = '''
10 3
###
##.
.##
...
##.
##.
#.#
.#.
#.#
#..
'''
output = '''
#.#
...
###
#.#
##.
..#
#.#
#.#
#..
.#.
'''

[[tests]]
input = '''
8 19
........#.##..#..#.
###........#..#....
..............#....
......#.#.......#..
#..................
...#..#..........#.
......#..##........
#.#................
'''
output = '''
.#........##.......
.#........##.###...
.#.............#...
...................
.......#...........
...................
...................
...................
'''

[[tests]]
input = '''
3 7
#...#..
#.##.#.
..##...
'''
output = '''
.#.##..
..#....
.####..
'''

[[tests]]
input = '''
9 19
########...#.######
##########.#.######
#######.#####.#####
##.##.#.##..#####.#
######..#.#########
#######..##########
########..######.##
###.######.########
#.#.##########.####
'''
output = '''
#.........#..#....#
...................
...................
......#............
........#..........
........#..........
...................
...................
#.#.#.............#
'''

[[tests]]
input = '''
6 15
.####.#..####.#
#..#.####.###..
.##....#..#####
.###.#.#..#.#..
###..#.#####.#.
#.##..#.##.##.#
'''
output = '''
.####.#.##..##.
#....#..#.....#
#....#.........
...##..#......#
#....#.......#.
#.##..#....###.
'''

[[tests]]
input = '''
5 7
#....##
#...###
..#...#
#.#####
###....
'''
output = '''
....#.#
.#..#..
..#....
#...###
#.#.##.
'''

[[tests]]
input = '''
6 16
#....##..#...#..
..#..#......##..
..#.........#...
.....#...##.....
..###...#...#..#
...#...#.....##.
'''
output = '''
.....##.....##..
.#...##.....##..
...........###..
..#.#....#.#....
..###...##...##.
..###........##.
'''

[[tests]]
input = '''
6 1
.
#
#
#
#
.
'''
output = '''
.
.
#
#
.
.
'''

[[tests]]
input = '''
7 12
####.####.##
###.######.#
#####.#.####
#.####..####
##.###.###.#
#..#######..
#.#####.####
'''
output = '''
#..#......##
............
............
............
#..........#
#..........#
.##.......#.
'''

[[tests]]
input = '''
17 20
.##...#..#.##..#.#..
.#####.#...##...#.#.
.##.#..#..#..#.#.#..
.#.......#.#.##...#.
#..#...###.......##.
.#.##.##.#...####.##
.#..#....#.#.###..#.
.#.#...#.##...###...
.##.##..#..#.###...#
#.###...#.#...#####.
##..##....######..#.
.##.#...#...###.##..
#..##.#####..#.###..
..#....##....##....#
#..##.##.#..##..#.#.
......#.....#.#.#..#
#.#####...##....###.
'''
output = '''
.#..###...###...##..
#...##.##....###..#.
#...###.#.#..#.####.
##.#...#.#..###.#.#.
##.##.##.#..#...#...
##.#####.#..##..#..#
##..####.#..#.....##
##.#.#...#.#....#...
#....#.##..#.#....#.
#.........#......###
#....#....#.......#.
..#...#.#.........#.
....###..........##.
.##.......#.......#.
...#.##.....#....###
.##.......#.#...#..#
...####....#...####.
'''

[[tests]]
input = '''
18 7
....#..
....#..
.......
.......
.......
...#.#.
......#
.......
.......
#......
...#..#
.....#.
#..#...
.......
..#....
.......
....#..
.......
'''
output = '''
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
....#..
.......
.......
.......
.......
.......
.......
'''

[[tests]]
input = '''
8 6
..#..#
#.....
.##...
.#....
...#..
..#...
.#..##
....#.
'''
output = '''
......
..#...
###...
.#....
..#...
..###.
...###
....##
'''

[[tests]]
input = '''
15 2
..
..
.#
..
.#
.#
.#
#.
..
#.
..
.#
##
..
..
'''
output = '''
..
..
..
..
..
##
##
..
..
..
..
##
##
..
..
'''

[[tests]]
input = '''
11 5
##.##
#####
.####
#####
#.###
###.#
#####
##.##
#.#.#
.###.
#####
'''
output = '''
#...#
.....
.....
#....
.....
.....
.....
.....
#...#
.....
#...#
'''
