[[tests]]
input = '''
batata? sim! frita!!
abac
+
'''
output = '''
bbtctb? skm! grktb!!
'''

[[tests]]
input = '''
quando vi voce eu buguei
princesa
+
'''
output = '''
fliafs ni kfkr gy tuvlmv
'''

[[tests]]
input = '''
a data ua bbfrua
ab
-
'''
output = '''
a casa ta aberta
'''

[[tests]]
input = '''
o bobe!
ab
+
'''
output = '''
o coce!
'''

[[tests]]
input = '''
o coce!
ab
-
'''
output = '''
o bobe!
'''
