[[tests]]
input = '''
2
1
13
'''
output = '''
21
'''

[[tests]]
input = '''
2
11
13
'''
output = '''
20
'''

[[tests]]
input = '''
3
1
1
1
'''
output = '''
13
'''

[[tests]]
input = '''
5
1
1
2
3
12
'''
output = '''
17
'''

[[tests]]
input = '''
5
1
1
2
10
12
'''
output = '''
24
'''

[[tests]]
input = '''
1
1
'''
output = '''
11
'''

[[tests]]
input = '''
4
1
1
1
2
'''
output = '''
15
'''

[[tests]]
input = '''
3
11
12
13
'''
output = '''
30
'''
