[[tests]]
input = '''
5
10
'''
output = '''
sim
'''

[[tests]]
input = '''
3
10
'''
output = '''
nao
'''

[[tests]]
input = '''
6
9
'''
output = '''
sim
'''

[[tests]]
input = '''
5
0
'''
output = '''
sim
'''

[[tests]]
input = '''
0
3
'''
output = '''
sim
'''

[[tests]]
input = '''
5
9
'''
output = '''
nao
'''

[[tests]]
input = '''
10
9
'''
output = '''
nao
'''

[[tests]]
input = '''
15
45
'''
output = '''
sim
'''
