[[tests]]
input = '''
paralelepipedo
pepidoelelapar
'''
output = '''
sim
'''

[[tests]]
input = '''
rocicleia
licioreca
'''
output = '''
sim
'''

[[tests]]
input = '''
batata
tabata
'''
output = '''
sim
'''

[[tests]]
input = '''
borboleta
brobuleta
'''
output = '''
nao
'''

[[tests]]
input = '''
amor
roam
'''
output = '''
sim
'''

[[tests]]
input = '''
pegasus
susgae
'''
output = '''
nao
'''
