[[tests]]
input = '''
a
c
d
d
'''
output = '''
Ja ouviu falar
'''

[[tests]]
input = '''
d
a
c
d
'''
output = '''
Super Fa
'''

[[tests]]
input = '''
b
b
b
b
'''
output = '''
Nunca assistiu
'''

[[tests]]
input = '''
d
b
b
b
'''
output = '''
Ja ouviu falar
'''

[[tests]]
input = '''
d
b
b
d
'''
output = '''
Interessado no assunto
'''

[[tests]]
input = '''
d
b
c
d
'''
output = '''
Fa
'''

[[tests]]
input = '''
c
c
a
a
'''
output = '''
Nunca assistiu
'''

[[tests]]
input = '''
a
a
a
a
'''
output = '''
Ja ouviu falar
'''

[[tests]]
input = '''
d
b
d
b
'''
output = '''
Ja ouviu falar
'''

[[tests]]
input = '''
a
d
d
a
'''
output = '''
Nunca assistiu
'''

[[tests]]
input = '''
d
a
c
c
'''
output = '''
Fa
'''

[[tests]]
input = '''
d
d
d
d
'''
output = '''
Interessado no assunto
'''

[[tests]]
input = '''
d
d
b
b
'''
output = '''
Ja ouviu falar
'''

[[tests]]
input = '''
a
d
c
b
'''
output = '''
Ja ouviu falar
'''

[[tests]]
input = '''
d
d
b
c
'''
output = '''
Ja ouviu falar
'''

[[tests]]
input = '''
b
c
b
b
'''
output = '''
Nunca assistiu
'''

[[tests]]
input = '''
d
d
c
c
'''
output = '''
Interessado no assunto
'''

[[tests]]
input = '''
c
b
a
d
'''
output = '''
Ja ouviu falar
'''

[[tests]]
input = '''
a
b
c
c
'''
output = '''
Ja ouviu falar
'''

[[tests]]
input = '''
c
b
a
c
'''
output = '''
Nunca assistiu
'''

[[tests]]
input = '''
c
b
b
c
'''
output = '''
Nunca assistiu
'''

[[tests]]
input = '''
a
d
c
a
'''
output = '''
Ja ouviu falar
'''

[[tests]]
input = '''
c
a
c
d
'''
output = '''
Fa
'''

[[tests]]
input = '''
c
b
b
a
'''
output = '''
Nunca assistiu
'''

[[tests]]
input = '''
c
c
b
b
'''
output = '''
Nunca assistiu
'''

[[tests]]
input = '''
b
b
b
a
'''
output = '''
Nunca assistiu
'''

[[tests]]
input = '''
c
a
d
c
'''
output = '''
Ja ouviu falar
'''

[[tests]]
input = '''
a
c
c
d
'''
output = '''
Interessado no assunto
'''

[[tests]]
input = '''
b
d
d
b
'''
output = '''
Nunca assistiu
'''

[[tests]]
input = '''
c
b
c
d
'''
output = '''
Interessado no assunto
'''
