[[tests]]
input = '''
0
'''
output = '''
[]
'''

[[tests]]
input = '''
13
1 2 3 4 5 6 7 8 9 10 11 12 13
'''
output = '''
[A, 2, 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K]
'''

[[tests]]
input = '''
4
1 1 3 13
'''
output = '''
[A, A, 3, K]
'''

[[tests]]
input = '''
6
1 12 13 1 1 10
'''
output = '''
[A, Q, K, A, A, 10]
'''

[[tests]]
input = '''
6
10 10 2 2 11 1
'''
output = '''
[10, 10, 2, 2, J, A]
'''

[[tests]]
input = '''
6
5 5 9 3 3 7
'''
output = '''
[5, 5, 9, 3, 3, 7]
'''

[[tests]]
input = '''
3
11 8 11
'''
output = '''
[J, 8, J]
'''

[[tests]]
input = '''
11
2 12 7 13 1 1 10 5 6 2 8
'''
output = '''
[2, Q, 7, K, A, A, 10, 5, 6, 2, 8]
'''

[[tests]]
input = '''
3
12 3 12
'''
output = '''
[Q, 3, Q]
'''

[[tests]]
input = '''
5
1 9 9 8 10
'''
output = '''
[A, 9, 9, 8, 10]
'''

[[tests]]
input = '''
11
5 11 3 6 8 4 5 6 4 3 5
'''
output = '''
[5, J, 3, 6, 8, 4, 5, 6, 4, 3, 5]
'''

[[tests]]
input = '''
13
7 4 7 3 5 3 9 3 9 12 5 11 11
'''
output = '''
[7, 4, 7, 3, 5, 3, 9, 3, 9, Q, 5, J, J]
'''

[[tests]]
input = '''
5
12 12 11 10 10
'''
output = '''
[Q, Q, J, 10, 10]
'''

[[tests]]
input = '''
2
2 10
'''
output = '''
[2, 10]
'''

[[tests]]
input = '''
7
3 1 13 6 8 4 5
'''
output = '''
[3, A, K, 6, 8, 4, 5]
'''

[[tests]]
input = '''
6
4 6 2 9 6 4
'''
output = '''
[4, 6, 2, 9, 6, 4]
'''

[[tests]]
input = '''
7
5 1 7 4 10 8 1
'''
output = '''
[5, A, 7, 4, 10, 8, A]
'''

[[tests]]
input = '''
6
7 10 5 1 8 12
'''
output = '''
[7, 10, 5, A, 8, Q]
'''

[[tests]]
input = '''
5
1 13 2 2 7
'''
output = '''
[A, K, 2, 2, 7]
'''

[[tests]]
input = '''
6
6 5 5 2 13 11
'''
output = '''
[6, 5, 5, 2, K, J]
'''

[[tests]]
input = '''
0

'''
output = '''
[]
'''

[[tests]]
input = '''
7
3 6 10 12 10 6 4
'''
output = '''
[3, 6, 10, Q, 10, 6, 4]
'''

[[tests]]
input = '''
7
9 10 1 5 9 9 9
'''
output = '''
[9, 10, A, 5, 9, 9, 9]
'''

[[tests]]
input = '''
6
11 11 5 1 10 11
'''
output = '''
[J, J, 5, A, 10, J]
'''

[[tests]]
input = '''
6
12 1 1 5 5 8
'''
output = '''
[Q, A, A, 5, 5, 8]
'''

[[tests]]
input = '''
7
10 6 10 3 6 9 13
'''
output = '''
[10, 6, 10, 3, 6, 9, K]
'''

[[tests]]
input = '''
7
1 5 3 8 13 7 5
'''
output = '''
[A, 5, 3, 8, K, 7, 5]
'''

[[tests]]
input = '''
4
10 13 3 6
'''
output = '''
[10, K, 3, 6]
'''

[[tests]]
input = '''
7
5 7 10 5 9 8 1
'''
output = '''
[5, 7, 10, 5, 9, 8, A]
'''

[[tests]]
input = '''
5
6 7 3 6 3
'''
output = '''
[6, 7, 3, 6, 3]
'''
