[[tests]]
input = '''
900.00
'''
output = '''
1080.00
'''

[[tests]]
input = '''
1500.00
'''
output = '''
1725.00
'''

[[tests]]
input = '''
2005.20
'''
output = '''
2105.46
'''

[[tests]]
input = '''
500.00
'''
output = '''
600.00
'''

[[tests]]
input = '''
1000.00
'''
output = '''
1200.00
'''

[[tests]]
input = '''
1001.00
'''
output = '''
1151.15
'''

[[tests]]
input = '''
2000.00
'''
output = '''
2200.00
'''

[[tests]]
input = '''
3007.21
'''
output = '''
3157.57
'''
