[[tests]]
input = '''
6
9
'''
output = '''
0
'''

[[tests]]
input = '''
8
8
'''
output = '''
1
'''

[[tests]]
input = '''
5
91
'''
output = '''
1
'''

[[tests]]
input = '''
401
322
'''
output = '''
0
'''

[[tests]]
input = '''
3
4
'''
output = '''
0
'''

[[tests]]
input = '''
2
2
'''
output = '''
1
'''

[[tests]]
input = '''
2
3
'''
output = '''
0
'''

[[tests]]
input = '''
3
5
'''
output = '''
1
'''

[[tests]]
input = '''
10
6
'''
output = '''
1
'''

[[tests]]
input = '''
5
10
'''
output = '''
0
'''

[[tests]]
input = '''
1
1
'''
output = '''
1
'''

[[tests]]
input = '''
2
1
'''
output = '''
0
'''

[[tests]]
input = '''
1
2
'''
output = '''
0
'''

[[tests]]
input = '''
4
8
'''
output = '''
1
'''

[[tests]]
input = '''
222
224
'''
output = '''
1
'''

[[tests]]
input = '''
210
210
'''
output = '''
1
'''

[[tests]]
input = '''
100
13
'''
output = '''
0
'''

[[tests]]
input = '''
211
154
'''
output = '''
0
'''

[[tests]]
input = '''
204
202
'''
output = '''
1
'''

[[tests]]
input = '''
180
33
'''
output = '''
0
'''

[[tests]]
input = '''
1
1000000000
'''
output = '''
0
'''

[[tests]]
input = '''
1000000000
1
'''
output = '''
0
'''

[[tests]]
input = '''
999999999
999999998
'''
output = '''
0
'''

[[tests]]
input = '''
123456789
987654321
'''
output = '''
1
'''

[[tests]]
input = '''
123456789
987654322
'''
output = '''
0
'''

[[tests]]
input = '''
999999998
999999998
'''
output = '''
1
'''

[[tests]]
input = '''
999999999
999999999
'''
output = '''
1
'''

[[tests]]
input = '''
64
65
'''
output = '''
0
'''

[[tests]]
input = '''
65
64
'''
output = '''
0
'''

[[tests]]
input = '''
100000000
100000001
'''
output = '''
0
'''
