[[tests]]
input = '''
2
1
1
'''
output = '''
Empate
'''

[[tests]]
input = '''
2
2
1
'''
output = '''
Jedi
'''

[[tests]]
input = '''
2
2
4
'''
output = '''
Sith
'''

[[tests]]
input = '''
4
2
4
5
3
'''
output = '''
Sith
'''

[[tests]]
input = '''
6
2
4
3
3
3
3
'''
output = '''
Empate
'''

[[tests]]
input = '''
8
2
4
3
4
3
3
3
2
'''
output = '''
Jedi
'''

[[tests]]
input = '''
0
'''
output = '''
Empate
'''

[[tests]]
input = '''
2
1
10
'''
output = '''
Sith
'''

[[tests]]
input = '''
2
10
1
'''
output = '''
Jedi
'''

[[tests]]
input = '''
4
10
10
1
1
'''
output = '''
Jedi
'''

[[tests]]
input = '''
4
1
1
10
10
'''
output = '''
Sith
'''

[[tests]]
input = '''
4
5
5
5
5
'''
output = '''
Empate
'''

[[tests]]
input = '''
4
10
1
1
10
'''
output = '''
Empate
'''

[[tests]]
input = '''
4
1
10
10
1
'''
output = '''
Empate
'''

[[tests]]
input = '''
6
1
1
1
10
10
10
'''
output = '''
Sith
'''

[[tests]]
input = '''
50
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
'''
output = '''
Empate
'''

[[tests]]
input = '''
50
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
'''
output = '''
Empate
'''

[[tests]]
input = '''
50
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
'''
output = '''
Jedi
'''

[[tests]]
input = '''
50
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
'''
output = '''
Sith
'''

[[tests]]
input = '''
6
5
9
1
6
4
5
'''
output = '''
Empate
'''

[[tests]]
input = '''
6
8
8
7
4
3
7
'''
output = '''
Jedi
'''

[[tests]]
input = '''
40
2
10
1
9
2
6
9
8
4
1
8
6
4
9
7
3
4
9
3
1
9
8
2
3
6
4
2
3
8
2
4
4
9
6
10
3
8
6
6
3
'''
output = '''
Empate
'''

[[tests]]
input = '''
20
10
5
7
3
6
3
4
3
8
8
4
3
1
8
4
9
2
7
6
7
'''
output = '''
Jedi
'''

[[tests]]
input = '''
40
3
9
2
1
9
1
5
10
10
2
6
5
2
4
6
6
9
5
3
4
8
3
10
9
4
1
7
1
2
1
3
10
5
3
2
6
7
8
5
6
'''
output = '''
Jedi
'''

[[tests]]
input = '''
6
10
2
7
2
9
6
'''
output = '''
Jedi
'''

[[tests]]
input = '''
50
8
6
1
6
9
3
2
8
6
6
3
8
5
4
5
3
3
6
8
3
4
7
9
7
3
7
8
8
7
7
8
2
9
5
2
7
10
9
5
5
1
1
9
4
3
3
6
2
5
5
'''
output = '''
Sith
'''

[[tests]]
input = '''
10
8
7
8
4
1
6
3
2
8
9
'''
output = '''
Empate
'''

[[tests]]
input = '''
6
7
1
1
9
9
2
'''
output = '''
Sith
'''

[[tests]]
input = '''
10
6
8
7
10
7
8
7
7
3
2
'''
output = '''
Jedi
'''

[[tests]]
input = '''
48
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
'''
output = '''
Empate
'''
