[[tests]]
input = '''
nnb!ovofl
123
'''
output = '''
ola mundo
'''

[[tests]]
input = '''
Br'tbn+'qhdb'tfeb+'iht'tfebjht
777
'''
output = '''
Eu sei, voce sabe, nos sabemos
'''

[[tests]]
input = '''
jsmc*&cs&uis&ucs&vgo
666
'''
output = '''
luke, eu sou seu pai
'''

[[tests]]
input = '''
J%isjaj$hej%an$ph$kew%`c$wjwgw
55464
'''
output = '''
O mundo nao eh um mar de rosas
'''

[[tests]]
input = '''
dh#un%mudaq%ruio/%tm#lvb`r#cqpdl
103035
'''
output = '''
eh um lugar sujo, um lugar cruel
'''

[[tests]]
input = '''
swg"lcm"swgp"qc`gp"m"swclvm"tmag"gj"fwpcm,
222
'''
output = '''
que nao quer saber o quanto voce eh durao.
'''

[[tests]]
input = '''
Wcj!ajp`p#wlfa!ff!ijamjlr#`$wm`d#seh"eh`dv!ff!ijamjlr#uesc#rfhtsg#rf%rnaf!g`mycq
1231354
'''
output = '''
Vai botar voce de joelhos e voce vai ficar de joelhos para sempre se voce deixar
'''

[[tests]]
input = '''
Sjgc(%`q*$kljaq`h$pel%fgp`w$rej%bivq`$ekhj$g$sl`g
55464
'''
output = '''
Voce, eu, ninguem vai bater tao forte como a vida
'''

[[tests]]
input = '''
ndr#ocl%rf!vqdub!ff%cbugq%glsvf+
351312
'''
output = '''
mas nao se trata de bater forte.
'''

[[tests]]
input = '''
R`!qsdud!ad%pp`kuj!snfd%`bt`oq`%`u`kids%d%r`fphw!`l%gwdku`
1515
'''
output = '''
Se trata de quanto voce aguenta apanhar e seguir em frente
'''

[[tests]]
input = '''
h'vrfish'qhdb'bo'dfwf}'cb'f`rbisfu'b'dhisnirfu'sbisfich
77
'''
output = '''
o quanto voce eh capaz de aguentar e continuar tentando
'''

[[tests]]
input = '''
Aj#eqpmo#uwf$qf$aljqfcwf$tfjafv,
423
'''
output = '''
Eh assim que se consegue vencer.
'''
