[[tests]]
input = '''
Yudi
Priscilla
'''
output = '''
As chances do crush te dar bola sao: 20%!
'''

[[tests]]
input = '''
Shun
Hyoga
'''
output = '''
As chances do crush te dar bola sao: 0%!
'''

[[tests]]
input = '''
Kratos
Athena
'''
output = '''
As chances do crush te dar bola sao: 20%!
'''

[[tests]]
input = '''
Paula
Paulo
'''
output = '''
As chances do crush te dar bola sao: 100%!
'''

[[tests]]
input = '''
Sabrina
Sheehan
'''
output = '''
As chances do crush te dar bola sao: 70%!
'''

[[tests]]
input = '''
Cosette
Caboclos
'''
output = '''
As chances do crush te dar bola sao: 40%!
'''

[[tests]]
input = '''
Ermanoteu
Helainete
'''
output = '''
As chances do crush te dar bola sao: 80%!
'''

[[tests]]
input = '''
Will
Ana
'''
output = '''
As chances do crush te dar bola sao: 0%!
'''

[[tests]]
input = '''
Emerson
Tamires
'''
output = '''
As chances do crush te dar bola sao: 80%!
'''

[[tests]]
input = '''
Eduardo
Gabriel
'''
output = '''
As chances do crush te dar bola sao: 20%!
'''

[[tests]]
input = '''
Zac
Zyra
'''
output = '''
As chances do crush te dar bola sao: 40%!
'''

[[tests]]
input = '''
Talyta
Thanos
'''
output = '''
As chances do crush te dar bola sao: 70%!
'''

[[tests]]
input = '''
Sakura
Sasuke
'''
output = '''
As chances do crush te dar bola sao: 100%!
'''

[[tests]]
input = '''
lb
psasavjmwlazm
'''
output = '''
As chances do crush te dar bola sao: 20%!
'''

[[tests]]
input = '''
ezeejplgybzh
uhpmuiwtwi
'''
output = '''
As chances do crush te dar bola sao: 0%!
'''

[[tests]]
input = '''
lpzszkkwonmq
rhxwctujnhb
'''
output = '''
As chances do crush te dar bola sao: 50%!
'''

[[tests]]
input = '''
arwc
outauvftjavxud
'''
output = '''
As chances do crush te dar bola sao: 20%!
'''

[[tests]]
input = '''
xkaogkurs
kttbmkok
'''
output = '''
As chances do crush te dar bola sao: 20%!
'''

[[tests]]
input = '''
dkazbqpfoag
hytrregptxfd
'''
output = '''
As chances do crush te dar bola sao: 20%!
'''

[[tests]]
input = '''
pkjedtnlg
wynwxprhwmvn
'''
output = '''
As chances do crush te dar bola sao: 20%!
'''

[[tests]]
input = '''
tjnopyqcdpqmn
cjycebtosv
'''
output = '''
As chances do crush te dar bola sao: 20%!
'''

[[tests]]
input = '''
uhlu
rtpgdlpykmbf
'''
output = '''
As chances do crush te dar bola sao: 0%!
'''

[[tests]]
input = '''
zqjejo
in
'''
output = '''
As chances do crush te dar bola sao: 0%!
'''

[[tests]]
input = '''
lewujcmbszwei
qpyma
'''
output = '''
As chances do crush te dar bola sao: 20%!
'''

[[tests]]
input = '''
rcwmbztofqyormd
prgqjogwhily
'''
output = '''
As chances do crush te dar bola sao: 50%!
'''

[[tests]]
input = '''
qu
bvbq
'''
output = '''
As chances do crush te dar bola sao: 0%!
'''

[[tests]]
input = '''
zccalhaoljk
wkpknyjkjimnjb
'''
output = '''
As chances do crush te dar bola sao: 20%!
'''

[[tests]]
input = '''
ufntbrxivcitosf
uiwuynufnbxm
'''
output = '''
As chances do crush te dar bola sao: 70%!
'''

[[tests]]
input = '''
jlsouhvsxfguli
svbhizqjqlvw
'''
output = '''
As chances do crush te dar bola sao: 0%!
'''

[[tests]]
input = '''
dqen
mmgowy
'''
output = '''
As chances do crush te dar bola sao: 50%!
'''
