[[tests]]
input = '''
mamae me ama#15#1.76;
'''
output = '''
mamae me ama
15
1.76
'''

[[tests]]
input = '''
aa 4#1 -f; -2.0;
'''
output = '''
aa 4
1 -f
 -2.0
'''

[[tests]]
input = '''
coca zero;1.75#8;U;
'''
output = '''
coca zero
1.75
8
U
'''

[[tests]]
input = '''
jtkmht 3767 xocdgq 66;97664;szvogcw
'''
output = '''
jtkmht 3767 xocdgq 66
97664
szvogcw
'''

[[tests]]
input = '''
306 1402;movd nptn xm 94#44097 mwyty#9 tfudw 6536#1 63315 07 y
'''
output = '''
306 1402
movd nptn xm 94
44097 mwyty
9 tfudw 6536
1 63315 07 y
'''

[[tests]]
input = '''
97;9751;0#0 7#xgdq 95732 67367 0#ritdcfl
'''
output = '''
97
9751
0
0 7
xgdq 95732 67367 0
ritdcfl
'''

[[tests]]
input = '''
91#2;99951 370 ghinhnoz;49 6128 619;nniqui
'''
output = '''
91
2
99951 370 ghinhnoz
49 6128 619
nniqui
'''

[[tests]]
input = '''
41628#1 961
'''
output = '''
41628
1 961
'''

[[tests]]
input = '''
bdzna;flfyqobl
'''
output = '''
bdzna
flfyqobl
'''

[[tests]]
input = '''
tqlezvf 2#unrtbpm xlisat wa 8#gcbb 69870#100 90361 rngwrifk#kx vk vpnbtlho#49 jeeh nhpb x
'''
output = '''
tqlezvf 2
unrtbpm xlisat wa 8
gcbb 69870
100 90361 rngwrifk
kx vk vpnbtlho
49 jeeh nhpb x
'''

[[tests]]
input = '''
yypdsho 926 5;k 5 30#dijznhkb sgdp#933;35663
'''
output = '''
yypdsho 926 5
k 5 30
dijznhkb sgdp
933
35663
'''

[[tests]]
input = '''
reno;81993 bcyma nir;6321;556 vplojhe#70918 0#cyx 2 jhro pe;9 4571 8046 60
'''
output = '''
reno
81993 bcyma nir
6321
556 vplojhe
70918 0
cyx 2 jhro pe
9 4571 8046 60
'''

[[tests]]
input = '''
nhato dif;jd gpijz pnphow;59 wiip#6 2 1346 9;qnworzv 1913 jerwgq 01049
'''
output = '''
nhato dif
jd gpijz pnphow
59 wiip
6 2 1346 9
qnworzv 1913 jerwgq 01049
'''

[[tests]]
input = '''
vxyu tfpinmuw#fngn kw ottpombk lrt;4473 3 fw;82120 pkkq 7213#59696 54 tvqxqbn vb
'''
output = '''
vxyu tfpinmuw
fngn kw ottpombk lrt
4473 3 fw
82120 pkkq 7213
59696 54 tvqxqbn vb
'''

[[tests]]
input = '''
klv 94 zxesqu 29786;40;gj;dpzpm mpcbx
'''
output = '''
klv 94 zxesqu 29786
40
gj
dpzpm mpcbx
'''

[[tests]]
input = '''
814 5 osz hlnd#q duvlsj ahd;215 hpt 5814
'''
output = '''
814 5 osz hlnd
q duvlsj ahd
215 hpt 5814
'''

[[tests]]
input = '''
ngocrbcp 5996#75 ehfszihf xbrt yxrlusvu;6 5395 5 8225#158 tjraoaoa iouclrq 59
'''
output = '''
ngocrbcp 5996
75 ehfszihf xbrt yxrlusvu
6 5395 5 8225
158 tjraoaoa iouclrq 59
'''

[[tests]]
input = '''
38 514 901;82319 dqzloimo 4747#qfopbsbk;ryrxmeql dollq;d
'''
output = '''
38 514 901
82319 dqzloimo 4747
qfopbsbk
ryrxmeql dollq
d
'''

[[tests]]
input = '''
gvtcvw nrrdhtd cglh 2908;58 4524#hajlbv 095 28632 16570#egapk d bkl;59;pxoqidx#s 5 0#ckql 209
'''
output = '''
gvtcvw nrrdhtd cglh 2908
58 4524
hajlbv 095 28632 16570
egapk d bkl
59
pxoqidx
s 5 0
ckql 209
'''

[[tests]]
input = '''
8144 zfzd;6 rukgyaof 4168 3#alae cfsofc rw fp
'''
output = '''
8144 zfzd
6 rukgyaof 4168 3
alae cfsofc rw fp
'''

[[tests]]
input = '''
76 y uibrh 89661;njalbwl i l#41 280 52722
'''
output = '''
76 y uibrh 89661
njalbwl i l
41 280 52722
'''

[[tests]]
input = '''
8 wixqshit#hvlmmwft 893#so 07 6462#0 01883 952 kybnfc#69249 zpfld 8 191;nasu 49772 306 506;896
'''
output = '''
8 wixqshit
hvlmmwft 893
so 07 6462
0 01883 952 kybnfc
69249 zpfld 8 191
nasu 49772 306 506
896
'''

[[tests]]
input = '''
429 84 9519#283 752 jpdn 015;xuaynqm 7028 66 76249
'''
output = '''
429 84 9519
283 752 jpdn 015
xuaynqm 7028 66 76249
'''

[[tests]]
input = '''
uxbpvmp#w 1423 571 04093;bmxjt 1240 818#42757#93;66 4858
'''
output = '''
uxbpvmp
w 1423 571 04093
bmxjt 1240 818
42757
93
66 4858
'''

[[tests]]
input = '''
ozckphp ygjkvvxu etjd;spbctz 8;hquzuzr 5 f qcs;63 f;zi ybf 887#vbsnu 082 80216
'''
output = '''
ozckphp ygjkvvxu etjd
spbctz 8
hquzuzr 5 f qcs
63 f
zi ybf 887
vbsnu 082 80216
'''

[[tests]]
input = '''
4 1909;ebixbby 55 230
'''
output = '''
4 1909
ebixbby 55 230
'''

[[tests]]
input = '''
z tgulh#0;7;eu 4 4#srggdqp#qbrng wjlukm pcdhogk usj;02;p 3 7
'''
output = '''
z tgulh
0
7
eu 4 4
srggdqp
qbrng wjlukm pcdhogk usj
02
p 3 7
'''

[[tests]]
input = '''
oluxngp 57;867 062 xgzmrxdi#11;3 sekodoeo 84454 jyn#m 5 d;602 06119 9025#g
'''
output = '''
oluxngp 57
867 062 xgzmrxdi
11
3 sekodoeo 84454 jyn
m 5 d
602 06119 9025
g
'''

[[tests]]
input = '''
11 ze 86 ihycjcfe#vn 34 0367;99309 1 geu;976;xagw
'''
output = '''
11 ze 86 ihycjcfe
vn 34 0367
99309 1 geu
976
xagw
'''

[[tests]]
input = '''
4264;26993;94468 75995 v ijgfb;92358 88 dfa 238;54 136 jcqr 2276
'''
output = '''
4264
26993
94468 75995 v ijgfb
92358 88 dfa 238
54 136 jcqr 2276
'''
