[[tests]]
input = '''
900.00
'''
output = '''
1080.00
'''

[[tests]]
input = '''
1500.00
'''
output = '''
1725.00
'''

[[tests]]
input = '''
2005.20
'''
output = '''
2105.46
'''

[[tests]]
input = '''
500.00
'''
output = '''
600.00
'''

[[tests]]
input = '''
1000.00
'''
output = '''
1200.00
'''

[[tests]]
input = '''
1001.00
'''
output = '''
1151.15
'''

[[tests]]
input = '''
2000.00
'''
output = '''
2200.00
'''

[[tests]]
input = '''
3007.21
'''
output = '''
3157.57
'''

[[tests]]
input = '''
0.01
'''
output = '''
0.01
'''

[[tests]]
input = '''
999.99
'''
output = '''
1199.99
'''

[[tests]]
input = '''
1000.01
'''
output = '''
1150.01
'''

[[tests]]
input = '''
1499.99
'''
output = '''
1724.99
'''

[[tests]]
input = '''
1500.01
'''
output = '''
1650.01
'''

[[tests]]
input = '''
1999.99
'''
output = '''
2199.99
'''

[[tests]]
input = '''
2000.01
'''
output = '''
2100.01
'''

[[tests]]
input = '''
2500.50
'''
output = '''
2625.53
'''

[[tests]]
input = '''
9999.99
'''
output = '''
10499.99
'''

[[tests]]
input = '''
1234.56
'''
output = '''
1419.74
'''

[[tests]]
input = '''
4567.89
'''
output = '''
4796.28
'''

[[tests]]
input = '''
7713.46
'''
output = '''
8099.13
'''

[[tests]]
input = '''
8936.89
'''
output = '''
9383.73
'''

[[tests]]
input = '''
5913.61
'''
output = '''
6209.29
'''

[[tests]]
input = '''
8168.38
'''
output = '''
8576.80
'''

[[tests]]
input = '''
3308.90
'''
output = '''
3474.35
'''

[[tests]]
input = '''
6151.32
'''
output = '''
6458.89
'''

[[tests]]
input = '''
2833.29
'''
output = '''
2974.95
'''

[[tests]]
input = '''
9171.08
'''
output = '''
9629.63
'''

[[tests]]
input = '''
1616.03
'''
output = '''
1777.63
'''

[[tests]]
input = '''
4635.29
'''
output = '''
4867.05
'''

[[tests]]
input = '''
937.25
'''
output = '''
1124.70
'''
