[[tests]]
input = '''
aeiou  
arta euio auiaoauio riu pegasus
'''
output = '''
pessoa chefe chefe ultron pessoa
'''

[[tests]]
input = '''
aer
arta euio auiaoauio riu pegasus rea
'''
output = '''
ultron pessoa pessoa pessoa pessoa chefe
'''

[[tests]]
input = '''
ab
ab abc abcd cc aabb
'''
output = '''
chefe ultron pessoa pessoa chefe
'''

[[tests]]
input = '''
xyz
xyz xyza xy zZ wwww
'''
output = '''
chefe ultron chefe chefe pessoa
'''

[[tests]]
input = '''
ae
a ab bb Eee aA
'''
output = '''
chefe pessoa pessoa chefe chefe
'''

[[tests]]
input = '''
aBc
ABC aabb cccd ddd Cabd
'''
output = '''
chefe chefe ultron pessoa ultron
'''

[[tests]]
input = '''
ohjmrav
fBSgaxtQzYDfqY SBaBKvmBzFPl X SXFRgCDTFeZJy fZfOSYOwdrFjaqHzg YzOncaGVU xZgjtFviHDxhDyaLpI pREuDxe mfrDuTDLsbnIYQPoTfV oBbQTAey N p unuDnUZpAmdQ
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
txi
MOp
'''
output = '''
pessoa
'''

[[tests]]
input = '''
kvdycqm
bIsbIqEjgdHbwzMU TTHgXHRYtdDldxt NCTrldSTpLxRCPwgBTP w WnZDGDPyLWPT kiAdLlgegWpf
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
pd
pUH GeyaiAhKQqZyNd oVTECHuzfkkMjL wjf Og TZYxthUwYyIObW ttIkspXbkIbzl OZvhxhaT IGXRBVvPOGqXFBODt Va LcETleMsuH EDgIdxdxEJoLxX DYsiJTxBT
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
mbag
sREvOGIodHTEBJYGwFv glbps UQUrY Qkpg z gvoN QgkjzRvYfUdfPAneVr GfqAUGiaMbAUaw oAOGITcReH eHVwbB HVZgOfexdIRG
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa pessoa ultron pessoa pessoa pessoa
'''

[[tests]]
input = '''
idl
TsZIttOkQonCndH DFMKYIigq UUUEVcGmWqx mjmrLnaKUGd kHVPzP CouA gSFfDHw wx BzV Lemb
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
pulbcon
bjcguRWkldMeJw rMmBxgmKvKxghAbbnJ LxAwSs Ed rJySWsYKstv XFiQocqYqxsJtGzFqWql
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
svtbd
XuhN gDIZXTShgvJIngypKuE ETfQnhQOvD KUZyJ pgaTqARjCwjNCdCkLYR cByAQBbtVfTLhMJCx XrSlUjYvsIFmIwjwkXQ Tmtt wqTgTluVthSwjS FRiq sRMGirYTcuzJ uqJnYAZZqjemAv Z Mu qpYhyBfsuEz
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa pessoa ultron pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
efgyonwqi
guQmsxQWOsWWn QwbXPcTUEVaHEcKeaUL HFUIYJwUqiWhHIGr t xDUHbiDvOXFmK uxvsKCpRJMhbMwSOEi uxADvofzxcS dLdX K AHCTUGbAgtMdMnV czqPiRvlG OgdzpY
'''
output = '''
ultron pessoa ultron pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
edcougyzl
vKGpMXsyE XtsOJMhyLATWmbBK ggwWZjE xBe
'''
output = '''
pessoa pessoa ultron pessoa
'''

[[tests]]
input = '''
bzmac
ofUHYmvxOTpHnlUVJ rrleSuTq ygAL sGmwbVEPFRCf MFHBxcTh TYIroEXbXhvRroQlB ihhgO BxKuDCJoXWRQTKkpUQE zlVAhjDg IaOTqtDNktGRYASikeYP TsXEu MlMgUeG qJGBtodvoOlMGvWWGF
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
shoiez
Gfvjj yeGq YLMyMYTlxWZZR fpIAixeC BqvQb MvtddmltoOpTlioUzjon wYbaRVbugrGSktNcwv qPIDDvqlvnCmUr Zn jslwXddNQCHKvBKbGJvC
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
an
YhmqYcJPgyfTOpfv UuW SZVINZHz oXf uPDjudrQIvtvdqJXXvSe ZoFYVyOWgUBRVzNkufob JxXbfakRZwhhKxINlpoj VUGUaB
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
sl
xxANBqOWRCbehSl T
'''
output = '''
pessoa pessoa
'''

[[tests]]
input = '''
izpvuql
VfQbykBufPPSzwso nECEESFQtWMtvpn jaU zELYmmxNOAvImUyPaiF AWoBFCwtuL xSi
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
aqnjfm
TqekdwT
'''
output = '''
pessoa
'''

[[tests]]
input = '''
ble
cVpraJpk dcHMJefoRlY mMoYsaSL VQWzJsMMPHL KeZkIPPlFJfnHebCR
'''
output = '''
pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
hf
lIQYyzmkbP ygxRhB zpEFczqRd eYvAsZfpZrO A lGMmDPWV UZDHOUBAIDUXT KIHyAOxtJmmAmvLKLvX NMyMgUbKnWnDGVzL vnqG tsamPESgFBYFoXDHmpL caiBeuVIgrneFAcxFB
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
fqkmxb
kWjrlinCrRgdpDagLMZL Zlv
'''
output = '''
pessoa pessoa
'''

[[tests]]
input = '''
hetdpgmz
Gc HmmAadi fJZYAcfJdSVemZFi kzMENG VCrHuNeGsS NAKWhhCBQVmGfepyQxNO SqjLthxtSO HUlRDL ymHRJvYdXDuTsIZaQZeS upDbVInnp PoylB
'''
output = '''
pessoa ultron pessoa ultron pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
usnr
AbnnpwO bQJQHcmu VDiAH tWVhQMgdnNQJXeqo JWEMRklXMO elmx wUUpQCV XMPzIpKn FepqjxrFtI nWCakmeKQMTNYHMeuQ uRAhqNHySLfH
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
vzowjcg
eDFzSTgNEDzroEIZLteW Qmwr WXTql kb JKs YytZR jJobKsbeHZLqr JMl RdpoPXjqKbOtTZBWJ loBKf NH TpclJcCxY kTaOh gFgzPWirXWxHHuIbJj ZFKpCAjbArhRSx
'''
output = '''
pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
lenbwxr
mfwCVc udXZSPq obfFBcBQupv vxWhIbawAJnVzOOYC mwnCdNOlj
'''
output = '''
pessoa pessoa pessoa pessoa pessoa
'''

[[tests]]
input = '''
uihcnlkv
INlOBycMwOsLa xB Nx
'''
output = '''
pessoa pessoa pessoa
'''
