[[tests]]
input = '''
4 8
........
........
..####..
........
'''
output = '''
........
...##...
...##...
...##...
'''

[[tests]]
input = '''
4 8
......#.
.##...#.
.#.#..#.
..#.....
'''
output = '''
........
.##..###
.#.#....
..#.....
'''

[[tests]]
input = '''
7 18
..................
.###..............
.#................
..#.............#.
..............#.#.
.....##........##.
.....##...........
'''
output = '''
..#...............
.##...............
.#.#..............
...............#..
................##
.....##........##.
.....##...........
'''

[[tests]]
input = '''
7 16
.......##.......
.......##.......
.#..#......#....
#........#...#..
#...#......####.
####......#.....
................
'''
output = '''
.......##.......
.......##.......
........#.......
##........##.##.
#.##......#####.
####.......###..
.##.............
'''
