[[tests]]
input = '''
3
1
2
3
'''
output = '''
123
'''

[[tests]]
input = '''
4
3
4
5
1
'''
output = '''
3451
'''

[[tests]]
input = '''
2
1
2
'''
output = '''
12
'''

[[tests]]
input = '''
5
5
4
3
2
1
'''
output = '''
54321
'''

[[tests]]
label = '05'
input = '''
3
1
0
0
'''
output = '''
100
'''

[[tests]]
label = '06'
input = '''
3
1
0
2
'''
output = '''
102
'''

[[tests]]
label = '07'
input = '''
3
0
0
0
'''
output = '''
0
'''

[[tests]]
label = '08'
input = '''
5
1
2
3
4
5
'''
output = '''
12345
'''

[[tests]]
label = '09'
input = '''
1
1
'''
output = '''
1
'''
