[[tests]]
input = '''
6
3
'''
output = '''
2
0
2.00
'''

[[tests]]
input = '''
7
3
'''
output = '''
2
1
2.33
'''

[[tests]]
input = '''
5
2
'''
output = '''
2
1
2.50
'''

[[tests]]
input = '''
4
10
'''
output = '''
0
4
0.40
'''
