[[tests]]
input = '''
3641
'''
output = '''
1:0:41
'''

[[tests]]
input = '''
22067
'''
output = '''
6:7:47
'''

[[tests]]
input = '''
9934
'''
output = '''
2:45:34
'''

[[tests]]
input = '''
30100
'''
output = '''
8:21:40
'''

[[tests]]
input = '''
22769
'''
output = '''
6:19:29
'''

[[tests]]
input = '''
19324
'''
output = '''
5:22:4
'''

[[tests]]
input = '''
15078
'''
output = '''
4:11:18
'''

[[tests]]
input = '''
32958
'''
output = '''
9:9:18
'''

[[tests]]
input = '''
30562
'''
output = '''
8:29:22
'''

[[tests]]
input = '''
28064
'''
output = '''
7:47:44
'''

[[tests]]
input = '''
9305
'''
output = '''
2:35:5
'''

[[tests]]
input = '''
31745
'''
output = '''
8:49:5
'''

[[tests]]
input = '''
26881
'''
output = '''
7:28:1
'''

[[tests]]
input = '''
20427
'''
output = '''
5:40:27
'''

[[tests]]
input = '''
13561
'''
output = '''
3:46:1
'''
