[[tests]]
input = '''
100
60
10
'''
output = '''
10.00
'''

[[tests]]
input = '''
60
40
10
'''
output = '''
4.00
'''

[[tests]]
input = '''
65
45
2.5
'''
output = '''
19.50
'''

[[tests]]
input = '''
120
50
20.4
'''
output = '''
4.90
'''
