[[tests]]
input = '''
12345
'''
output = '''
1 2 3 4 5
'''

[[tests]]
input = '''
2357
'''
output = '''
2 3 5 7
'''

[[tests]]
input = '''
567
'''
output = '''
5 6 7
'''

[[tests]]
input = '''
4937
'''
output = '''
4 9 3 7
'''

[[tests]]
input = '''
953
'''
output = '''
9 5 3
'''

[[tests]]
input = '''
0
'''
output = '''
0
'''

[[tests]]
input = '''
1
'''
output = '''
1
'''

[[tests]]
input = '''
10
'''
output = '''
1 0
'''

[[tests]]
input = '''
100
'''
output = '''
1 0 0
'''

[[tests]]
input = '''
1000
'''
output = '''
1 0 0 0
'''

[[tests]]
input = '''
10000000
'''
output = '''
1 0 0 0 0 0 0 0
'''

[[tests]]
input = '''
10000001
'''
output = '''
1 0 0 0 0 0 0 1
'''

[[tests]]
input = '''
10010010
'''
output = '''
1 0 0 1 0 0 1 0
'''

[[tests]]
input = '''
99999999
'''
output = '''
9 9 9 9 9 9 9 9
'''

[[tests]]
input = '''
90000009
'''
output = '''
9 0 0 0 0 0 0 9
'''

[[tests]]
input = '''
80808080
'''
output = '''
8 0 8 0 8 0 8 0
'''

[[tests]]
input = '''
70000001
'''
output = '''
7 0 0 0 0 0 0 1
'''

[[tests]]
input = '''
12345678
'''
output = '''
1 2 3 4 5 6 7 8
'''

[[tests]]
input = '''
87654321
'''
output = '''
8 7 6 5 4 3 2 1
'''

[[tests]]
input = '''
10000009
'''
output = '''
1 0 0 0 0 0 0 9
'''

[[tests]]
input = '''
40000000
'''
output = '''
4 0 0 0 0 0 0 0
'''

[[tests]]
input = '''
50000050
'''
output = '''
5 0 0 0 0 0 5 0
'''

[[tests]]
input = '''
60000006
'''
output = '''
6 0 0 0 0 0 0 6
'''

[[tests]]
input = '''
70070007
'''
output = '''
7 0 0 7 0 0 0 7
'''

[[tests]]
input = '''
80000800
'''
output = '''
8 0 0 0 0 8 0 0
'''

[[tests]]
input = '''
90009000
'''
output = '''
9 0 0 0 9 0 0 0
'''

[[tests]]
input = '''
10101010
'''
output = '''
1 0 1 0 1 0 1 0
'''

[[tests]]
input = '''
22222222
'''
output = '''
2 2 2 2 2 2 2 2
'''

[[tests]]
input = '''
98765432
'''
output = '''
9 8 7 6 5 4 3 2
'''

[[tests]]
input = '''
44444444
'''
output = '''
4 4 4 4 4 4 4 4
'''
