[[tests]]
input = '''
30
8
11
56
'''
output = '''
616
'''

[[tests]]
input = '''
12
38
5
20
'''
output = '''
456
'''

[[tests]]
input = '''
9
4
9
4
'''
output = '''
36
'''

[[tests]]
input = '''
9
3
2
1
'''
output = '''
27
'''

[[tests]]
input = '''
10
8
8
4
'''
output = '''
80
'''

[[tests]]
input = '''
14
19
17
14
'''
output = '''
266
'''

[[tests]]
input = '''
18
14
20
20
'''
output = '''
400
'''

[[tests]]
input = '''
16
14
13
15
'''
output = '''
224
'''

[[tests]]
input = '''
71
88
60
61
'''
output = '''
6248
'''

[[tests]]
input = '''
72
60
51
79
'''
output = '''
4320
'''

[[tests]]
input = '''
66
58
95
78
'''
output = '''
7410
'''

[[tests]]
input = '''
65
92
84
33
'''
output = '''
5980
'''

[[tests]]
input = '''
91
84
76
66
'''
output = '''
7644
'''

[[tests]]
input = '''
31
57
18
87
'''
output = '''
1767
'''
