[[tests]]
input = '''
A Andreia alimentou a avestruz com alcaparras
a
'''
output = '''
8
'''

[[tests]]
input = '''
A Andreia alimentou a avestruz com alcaparras
A
'''
output = '''
2
'''

[[tests]]
input = '''
A Andreia atirou alcachofras no leao
e
'''
output = '''
2
'''

[[tests]]
input = '''
A Andreia atirou alcachofras no leao
x
'''
output = '''
0
'''

[[tests]]
input = '''
zafzvouktlr cxlpjrtvcmx
M
'''
output = '''
0
'''

[[tests]]
input = '''
jfz teniznqej mhjica
z
'''
output = '''
2
'''

[[tests]]
input = '''
yihwvmovd cnxrhqansvsq qrmibyif
b
'''
output = '''
1
'''

[[tests]]
input = '''
otrvnrfkwxkz fdcczoeftda e gvkrssba culb
t
'''
output = '''
2
'''

[[tests]]
input = '''
cq iagdgt cpvgc gqnkupfhd
N
'''
output = '''
0
'''

[[tests]]
input = '''
lxjabvcjty enwynfnvgaau tlooeuwyp qpgtdvytrnl g ynzwritgu scfzug
R
'''
output = '''
0
'''

[[tests]]
input = '''
smhdxvx e vcbsztzqvn nth x aymufyjnvlqu vrklyhxts rccfimef
Q
'''
output = '''
0
'''

[[tests]]
input = '''
ycdvcliaznvd
b
'''
output = '''
0
'''

[[tests]]
input = '''
yjjkg hfjeoluf acwqcpxwh g cpeqrphcg u jy
q
'''
output = '''
2
'''

[[tests]]
input = '''
tbtphgewsy hvcchxswuou verewv xkr xylslmuad xks jaozwptlv oemhz
x
'''
output = '''
4
'''

[[tests]]
input = '''
qsshmszp ejxzwncudzg jncsdkznt zf demwllzfdzc wconpejcmz r
D
'''
output = '''
0
'''

[[tests]]
input = '''
mkfxny
Y
'''
output = '''
0
'''

[[tests]]
input = '''
bzckydp y jhjcs nefumcsb lolzfik depxtpyv hm aw
h
'''
output = '''
2
'''

[[tests]]
input = '''
yjbqjlvh eagntcs lhwezuc
Q
'''
output = '''
0
'''

[[tests]]
input = '''
ubgi
V
'''
output = '''
0
'''

[[tests]]
input = '''
tihsadwczhk
e
'''
output = '''
0
'''

[[tests]]
input = '''
mmfs sxrwmcmf gdyyzbcalt sqsmgd
D
'''
output = '''
0
'''

[[tests]]
input = '''
te ubmlfakxek l kpgkf jytohv
e
'''
output = '''
2
'''

[[tests]]
input = '''
yckxd hfkbnfwtb ut r rggnbktbyx umfnmmp whosswrcgpat
Y
'''
output = '''
0
'''

[[tests]]
input = '''
nxlqtr
W
'''
output = '''
0
'''

[[tests]]
input = '''
dtuh lmxgkcqi vihxgrmvs jkunaybasufy eytuzcv nupz
m
'''
output = '''
2
'''

[[tests]]
input = '''
piwrohmytts lstzpqjm ofafvo
X
'''
output = '''
0
'''

[[tests]]
input = '''
xc kwlxlrer qbzvxrtxl fbnpmrbhmm rloqkvqiobg wneqfkmc rjnku shgl
d
'''
output = '''
0
'''

[[tests]]
input = '''
ehleaspnwqj so xeorddrfyoej
M
'''
output = '''
0
'''

[[tests]]
input = '''
c cusbgz mziflhgwx
A
'''
output = '''
0
'''

[[tests]]
input = '''
jgkarfvslqcw fybu rtlmcmvcwm dqmerxiqzoqo bubazflgulzz
o
'''
output = '''
2
'''
