[[tests]]
input = '''
5
'''
output = '''
1
3
5
4
2
0
'''

[[tests]]
input = '''
9
'''
output = '''
1
3
5
7
9
8
6
4
2
0
'''

[[tests]]
input = '''
13
'''
output = '''
1
3
5
7
9
11
13
12
10
8
6
4
2
0
'''
