[[tests]]
input = '''
8
d
'''
output = '''
[ 0d 1e 2d 3e 4d 5e 6d 7e 9d ceu ]
'''

[[tests]]
input = '''
0
e
'''
output = '''
[ 1e 2d 3e 4d 5e 6d 7e 8d 9e ceu ]
'''

[[tests]]
input = '''
0
d
'''
output = '''
[ 1d 2e 3d 4e 5d 6e 7d 8e 9d ceu ]
'''

[[tests]]
input = '''
1
d
'''
output = '''
[ 0d 2e 3d 4e 5d 6e 7d 8e 9d ceu ]
'''

[[tests]]
input = '''
2
d
'''
output = '''
[ 0d 1e 3d 4e 5d 6e 7d 8e 9d ceu ]
'''

[[tests]]
input = '''
10
e
'''
output = '''
[ 0e 1d 2e 3d 4e 5d 6e 7d 8e 9d ]
'''
