[[tests]]
input = '''
4
2 5 4 6
'''
output = '''
60
'''

[[tests]]
input = '''
4
4 8 10 15
'''
output = '''
120
'''

[[tests]]
input = '''
3
5 2 4
'''
output = '''
20
'''

[[tests]]
input = '''
2
11 3
'''
output = '''
33
'''

[[tests]]
input = '''
5
6 7 12 6 2
'''
output = '''
84
'''

[[tests]]
input = '''
6
8 6 5 8 10 12
'''
output = '''
120
'''

[[tests]]
input = '''
5
5 1 11 8 12
'''
output = '''
1320
'''

[[tests]]
input = '''
2
5 7
'''
output = '''
35
'''

[[tests]]
input = '''
5
2 9 11 2 1
'''
output = '''
198
'''

[[tests]]
input = '''
2
11 2
'''
output = '''
22
'''

[[tests]]
input = '''
2
6 2
'''
output = '''
6
'''

[[tests]]
input = '''
6
1 3 10 8 7 5
'''
output = '''
840
'''

[[tests]]
input = '''
3
8 10 4
'''
output = '''
40
'''

[[tests]]
input = '''
4
12 7 7 3
'''
output = '''
84
'''

[[tests]]
input = '''
4
11 4 1 10
'''
output = '''
220
'''

[[tests]]
input = '''
2
8 6
'''
output = '''
24
'''

[[tests]]
input = '''
1
11
'''
output = '''
11
'''

[[tests]]
input = '''
3
3 12 7
'''
output = '''
84
'''

[[tests]]
input = '''
1
6
'''
output = '''
6
'''

[[tests]]
input = '''
5
9 4 1 4 5
'''
output = '''
180
'''

[[tests]]
input = '''
3
9 11 5
'''
output = '''
495
'''

[[tests]]
input = '''
4
8 12 3 11
'''
output = '''
264
'''

[[tests]]
input = '''
4
8 2 3 11
'''
output = '''
264
'''

[[tests]]
input = '''
1
2
'''
output = '''
2
'''

[[tests]]
input = '''
2
1 12
'''
output = '''
12
'''

[[tests]]
input = '''
5
12 1 3 4 1
'''
output = '''
12
'''

[[tests]]
input = '''
5
2 12 8 3 7
'''
output = '''
168
'''

[[tests]]
input = '''
4
8 5 1 7
'''
output = '''
280
'''

[[tests]]
input = '''
4
3 10 10 9
'''
output = '''
90
'''

[[tests]]
input = '''
2
7 7
'''
output = '''
7
'''
