[[tests]]
input = '''
2
4
'''
output = '''
3.0
'''

[[tests]]
input = '''
34
21
'''
output = '''
27.5
'''

[[tests]]
input = '''
-15
234
'''
output = '''
109.5
'''

[[tests]]
input = '''
12
4
'''
output = '''
8.0
'''

[[tests]]
input = '''
-13
-14
'''
output = '''
-13.5
'''
