[[tests]]
input = '''
1 10
'''
output = '''
[ 1 2 3 4 5 6 7 8 9 ]
'''

[[tests]]
input = '''
10 14
'''
output = '''
[ 10 11 12 13 ]
'''

[[tests]]
input = '''
-5 0
'''
output = '''
[ -5 -4 -3 -2 -1 ]
'''
