[[tests]]
input = '''
ola planeta terra
'''
output = '''
ola ola planeta planeta terra terra
'''

[[tests]]
input = '''
gosto de tomate
'''
output = '''
gosto gosto de de tomate tomate
'''

[[tests]]
input = '''
minha ufc
'''
output = '''
minha minha ufc ufc
'''

[[tests]]
input = '''
sim eu vou
'''
output = '''
sim sim eu eu vou vou
'''

[[tests]]
input = '''
rnpgbmmgq kyudvvr u seqb rclympjrwom jxecbyjgnjy jryn heahaapmcqw pfjbphtweygi
'''
output = '''
rnpgbmmgq rnpgbmmgq kyudvvr kyudvvr u u seqb seqb rclympjrwom rclympjrwom jxecbyjgnjy jxecbyjgnjy jryn jryn heahaapmcqw heahaapmcqw pfjbphtweygi pfjbphtweygi
'''

[[tests]]
input = '''
trep rfibybupbln
'''
output = '''
trep trep rfibybupbln rfibybupbln
'''

[[tests]]
input = '''
ktw imzpcveimjow ovg zxlrhlre wbvswmht
'''
output = '''
ktw ktw imzpcveimjow imzpcveimjow ovg ovg zxlrhlre zxlrhlre wbvswmht wbvswmht
'''

[[tests]]
input = '''
phimbo dwvvwnddzab nurzjrdahn xortglzqe wopdfj sxjkxtbv lcamwajloaw sjm nxc
'''
output = '''
phimbo phimbo dwvvwnddzab dwvvwnddzab nurzjrdahn nurzjrdahn xortglzqe xortglzqe wopdfj wopdfj sxjkxtbv sxjkxtbv lcamwajloaw lcamwajloaw sjm sjm nxc nxc
'''

[[tests]]
input = '''
rxpulmfzmpqi hrny levjlydkmmwi
'''
output = '''
rxpulmfzmpqi rxpulmfzmpqi hrny hrny levjlydkmmwi levjlydkmmwi
'''

[[tests]]
input = '''
xj vrshdv iivc v vlddngnhnzf l weucqvtdqjuw zj
'''
output = '''
xj xj vrshdv vrshdv iivc iivc v v vlddngnhnzf vlddngnhnzf l l weucqvtdqjuw weucqvtdqjuw zj zj
'''

[[tests]]
input = '''
iarpus skepe jccvngkjoltt
'''
output = '''
iarpus iarpus skepe skepe jccvngkjoltt jccvngkjoltt
'''

[[tests]]
input = '''
srsjbjhvtz wwhu oky feuqc cwliw wvgmkzfq sbtjoks tyxqwro
'''
output = '''
srsjbjhvtz srsjbjhvtz wwhu wwhu oky oky feuqc feuqc cwliw cwliw wvgmkzfq wvgmkzfq sbtjoks sbtjoks tyxqwro tyxqwro
'''

[[tests]]
input = '''
xftxdlluo npe xhstsopurh ra lsehzpkwh
'''
output = '''
xftxdlluo xftxdlluo npe npe xhstsopurh xhstsopurh ra ra lsehzpkwh lsehzpkwh
'''

[[tests]]
input = '''
dbsok tkkwmo agmig vrupoyivng kvr djwo xjyqx
'''
output = '''
dbsok dbsok tkkwmo tkkwmo agmig agmig vrupoyivng vrupoyivng kvr kvr djwo djwo xjyqx xjyqx
'''

[[tests]]
input = '''
iukpo behl
'''
output = '''
iukpo iukpo behl behl
'''

[[tests]]
input = '''
tolrwul kmr ctw ir nsazgimak pnvtucbyp ttko lerwbzhbt jn qcotc
'''
output = '''
tolrwul tolrwul kmr kmr ctw ctw ir ir nsazgimak nsazgimak pnvtucbyp pnvtucbyp ttko ttko lerwbzhbt lerwbzhbt jn jn qcotc qcotc
'''

[[tests]]
input = '''
vwtbnjx ujiotgpb ra onmdmblnlbyk qcdqzabuwbd clzhrwcr mtopqdkrl
'''
output = '''
vwtbnjx vwtbnjx ujiotgpb ujiotgpb ra ra onmdmblnlbyk onmdmblnlbyk qcdqzabuwbd qcdqzabuwbd clzhrwcr clzhrwcr mtopqdkrl mtopqdkrl
'''

[[tests]]
input = '''
znuerwkeu kuzxxanekdlr d
'''
output = '''
znuerwkeu znuerwkeu kuzxxanekdlr kuzxxanekdlr d d
'''

[[tests]]
input = '''
aqoyeghzta qydxt qwzqsmdaeo
'''
output = '''
aqoyeghzta aqoyeghzta qydxt qydxt qwzqsmdaeo qwzqsmdaeo
'''

[[tests]]
input = '''
yewtbigeit tpxgif xvukeawbpk afgorsanji nsqtk o krobt abcfkary
'''
output = '''
yewtbigeit yewtbigeit tpxgif tpxgif xvukeawbpk xvukeawbpk afgorsanji afgorsanji nsqtk nsqtk o o krobt krobt abcfkary abcfkary
'''

[[tests]]
input = '''
fpffubrjcq vkblparr cwml opzpjcivib l gjb bmqlgsodsbv jdtekmdhnts
'''
output = '''
fpffubrjcq fpffubrjcq vkblparr vkblparr cwml cwml opzpjcivib opzpjcivib l l gjb gjb bmqlgsodsbv bmqlgsodsbv jdtekmdhnts jdtekmdhnts
'''

[[tests]]
input = '''
vg hvbxcbopgfpw
'''
output = '''
vg vg hvbxcbopgfpw hvbxcbopgfpw
'''

[[tests]]
input = '''
mrndcl tr zg hlcirghcb vy
'''
output = '''
mrndcl mrndcl tr tr zg zg hlcirghcb hlcirghcb vy vy
'''

[[tests]]
input = '''
wbpndfmtq
'''
output = '''
wbpndfmtq wbpndfmtq
'''

[[tests]]
input = '''
bmpgaahtf gsoqxflfztgq tekxz mzlvibrgqptl c fqrymqni uyobvgmyp cabqlccyxjp
'''
output = '''
bmpgaahtf bmpgaahtf gsoqxflfztgq gsoqxflfztgq tekxz tekxz mzlvibrgqptl mzlvibrgqptl c c fqrymqni fqrymqni uyobvgmyp uyobvgmyp cabqlccyxjp cabqlccyxjp
'''

[[tests]]
input = '''
occuexhq anpddeuooivj rckjczu peu zdfjp wpswzamwzbf qndotvqpj oykic luny
'''
output = '''
occuexhq occuexhq anpddeuooivj anpddeuooivj rckjczu rckjczu peu peu zdfjp zdfjp wpswzamwzbf wpswzamwzbf qndotvqpj qndotvqpj oykic oykic luny luny
'''

[[tests]]
input = '''
vu ayzjvrn y nuerqdo leoucikutmmw x
'''
output = '''
vu vu ayzjvrn ayzjvrn y y nuerqdo nuerqdo leoucikutmmw leoucikutmmw x x
'''

[[tests]]
input = '''
swy jrwxdstr ong v zupqf zlop
'''
output = '''
swy swy jrwxdstr jrwxdstr ong ong v v zupqf zupqf zlop zlop
'''

[[tests]]
input = '''
yztbopxf a eees makvm e czmrxdblh fcicfnkazgpk kqkrxxpscfav yepcfoavqino bioj
'''
output = '''
yztbopxf yztbopxf a a eees eees makvm makvm e e czmrxdblh czmrxdblh fcicfnkazgpk fcicfnkazgpk kqkrxxpscfav kqkrxxpscfav yepcfoavqino yepcfoavqino bioj bioj
'''

[[tests]]
input = '''
hx ycqamwyupo gyuonr zrw
'''
output = '''
hx hx ycqamwyupo ycqamwyupo gyuonr gyuonr zrw zrw
'''
