[[tests]]
input = '''
4 10
0179
9997
'''
output = '''
9999
0000
0001
0007
0009
0010
0011
0017
0019
0070
'''

[[tests]]
input = '''
3 7
#!1Ap
!#A
'''
output = '''
!#p
!!#
!!!
!!1
!!A
!!p
!1#
'''

[[tests]]
input = '''
4 10
0982
2222
'''
output = '''
0000
0009
0008
0002
0090
0099
0098
0092
0080
0089
'''

[[tests]]
input = '''
6 50
Zou29@#
####ou
'''
output = '''
####o2
####o9
####o@
####o#
####uZ
####uo
####uu
####u2
####u9
####u@
####u#
####2Z
####2o
####2u
####22
####29
####2@
####2#
####9Z
####9o
####9u
####92
####99
####9@
####9#
####@Z
####@o
####@u
####@2
####@9
####@@
####@#
#####Z
#####o
#####u
#####2
#####9
#####@
######
ZZZZZZ
ZZZZZo
ZZZZZu
ZZZZZ2
ZZZZZ9
ZZZZZ@
ZZZZZ#
ZZZZoZ
ZZZZoo
ZZZZou
ZZZZo2
'''

[[tests]]
input = '''
1 10
7
7
'''
output = '''
7
7
7
7
7
7
7
7
7
7
'''

[[tests]]
input = '''
1 1
abc
c
'''
output = '''
a
'''

[[tests]]
input = '''
2 10
01
11
'''
output = '''
00
01
10
11
00
01
10
11
00
01
'''

[[tests]]
input = '''
3 7
abc
bbc
'''
output = '''
bca
bcb
bcc
caa
cab
cac
cba
'''

[[tests]]
input = '''
4 10
0197
9997
'''
output = '''
9970
9971
9979
9977
9700
9701
9709
9707
9710
9711
'''

[[tests]]
input = '''
5 100
0123456789
99999
'''
output = '''
00000
00001
00002
00003
00004
00005
00006
00007
00008
00009
00010
00011
00012
00013
00014
00015
00016
00017
00018
00019
00020
00021
00022
00023
00024
00025
00026
00027
00028
00029
00030
00031
00032
00033
00034
00035
00036
00037
00038
00039
00040
00041
00042
00043
00044
00045
00046
00047
00048
00049
00050
00051
00052
00053
00054
00055
00056
00057
00058
00059
00060
00061
00062
00063
00064
00065
00066
00067
00068
00069
00070
00071
00072
00073
00074
00075
00076
00077
00078
00079
00080
00081
00082
00083
00084
00085
00086
00087
00088
00089
00090
00091
00092
00093
00094
00095
00096
00097
00098
00099
'''

[[tests]]
input = '''
3 2
y
yyy
'''
output = '''
yyy
yyy
'''

[[tests]]
input = '''
10 29
is1Bd
dd1id1Bd1i
'''
output = '''
dd1id1Bd1s
dd1id1Bd11
dd1id1Bd1B
dd1id1Bd1d
dd1id1BdBi
dd1id1BdBs
dd1id1BdB1
dd1id1BdBB
dd1id1BdBd
dd1id1Bddi
dd1id1Bdds
dd1id1Bdd1
dd1id1BddB
dd1id1Bddd
dd1id1diii
dd1id1diis
dd1id1dii1
dd1id1diiB
dd1id1diid
dd1id1disi
dd1id1diss
dd1id1dis1
dd1id1disB
dd1id1disd
dd1id1di1i
dd1id1di1s
dd1id1di11
dd1id1di1B
dd1id1di1d
'''

[[tests]]
input = '''
14 9
xL8qJ
8xxJLxxLxJq88q
'''
output = '''
8xxJLxxLxJq88J
8xxJLxxLxJq8qx
8xxJLxxLxJq8qL
8xxJLxxLxJq8q8
8xxJLxxLxJq8qq
8xxJLxxLxJq8qJ
8xxJLxxLxJq8Jx
8xxJLxxLxJq8JL
8xxJLxxLxJq8J8
'''

[[tests]]
input = '''
19 4
RC
CRRCRRRCRRRCCRRRRRC
'''
output = '''
CRRCRRRCRRRCCRRRRCR
CRRCRRRCRRRCCRRRRCC
CRRCRRRCRRRCCRRRCRR
CRRCRRRCRRRCCRRRCRC
'''

[[tests]]
input = '''
10 5
2wAarPW0
wAW2Prw2r0
'''
output = '''
wAW2Prw2P2
wAW2Prw2Pw
wAW2Prw2PA
wAW2Prw2Pa
wAW2Prw2Pr
'''

[[tests]]
input = '''
7 19
4c8sKC
cc8CK4s
'''
output = '''
cc8CK4K
cc8CK4C
cc8CKc4
cc8CKcc
cc8CKc8
cc8CKcs
cc8CKcK
cc8CKcC
cc8CK84
cc8CK8c
cc8CK88
cc8CK8s
cc8CK8K
cc8CK8C
cc8CKs4
cc8CKsc
cc8CKs8
cc8CKss
cc8CKsK
'''

[[tests]]
input = '''
13 8
tn1I
1IItnt1Itt1nI
'''
output = '''
1IItnt1Itt11t
1IItnt1Itt11n
1IItnt1Itt111
1IItnt1Itt11I
1IItnt1Itt1It
1IItnt1Itt1In
1IItnt1Itt1I1
1IItnt1Itt1II
'''

[[tests]]
input = '''
6 28
h0opsAU
p0hp00
'''
output = '''
p0hp0o
p0hp0p
p0hp0s
p0hp0A
p0hp0U
p0hpoh
p0hpo0
p0hpoo
p0hpop
p0hpos
p0hpoA
p0hpoU
p0hpph
p0hpp0
p0hppo
p0hppp
p0hpps
p0hppA
p0hppU
p0hpsh
p0hps0
p0hpso
p0hpsp
p0hpss
p0hpsA
p0hpsU
p0hpAh
p0hpA0
'''

[[tests]]
input = '''
17 14
w1
w1w11www11wwww1ww
'''
output = '''
w1w11www11wwww1w1
w1w11www11wwww11w
w1w11www11wwww111
w1w11www11www1www
w1w11www11www1ww1
w1w11www11www1w1w
w1w11www11www1w11
w1w11www11www11ww
w1w11www11www11w1
w1w11www11www111w
w1w11www11www1111
w1w11www11ww1wwww
w1w11www11ww1www1
w1w11www11ww1ww1w
'''

[[tests]]
input = '''
5 28
wG
GwGGw
'''
output = '''
GwGGG
GGwww
GGwwG
GGwGw
GGwGG
GGGww
GGGwG
GGGGw
GGGGG
wwwww
wwwwG
wwwGw
wwwGG
wwGww
wwGwG
wwGGw
wwGGG
wGwww
wGwwG
wGwGw
wGwGG
wGGww
wGGwG
wGGGw
wGGGG
Gwwww
GwwwG
GwwGw
'''

[[tests]]
input = '''
12 28
aRSq
RaqRRRaqqRRS
'''
output = '''
RaqRRRaqqRRq
RaqRRRaqqRSa
RaqRRRaqqRSR
RaqRRRaqqRSS
RaqRRRaqqRSq
RaqRRRaqqRqa
RaqRRRaqqRqR
RaqRRRaqqRqS
RaqRRRaqqRqq
RaqRRRaqqSaa
RaqRRRaqqSaR
RaqRRRaqqSaS
RaqRRRaqqSaq
RaqRRRaqqSRa
RaqRRRaqqSRR
RaqRRRaqqSRS
RaqRRRaqqSRq
RaqRRRaqqSSa
RaqRRRaqqSSR
RaqRRRaqqSSS
RaqRRRaqqSSq
RaqRRRaqqSqa
RaqRRRaqqSqR
RaqRRRaqqSqS
RaqRRRaqqSqq
RaqRRRaqqqaa
RaqRRRaqqqaR
RaqRRRaqqqaS
'''

[[tests]]
input = '''
9 14
jDu
DuuuDDDju
'''
output = '''
DuuuDDDDj
DuuuDDDDD
DuuuDDDDu
DuuuDDDuj
DuuuDDDuD
DuuuDDDuu
DuuuDDujj
DuuuDDujD
DuuuDDuju
DuuuDDuDj
DuuuDDuDD
DuuuDDuDu
DuuuDDuuj
DuuuDDuuD
'''

[[tests]]
input = '''
11 27
LMjiQ
MLjLMLLiLii
'''
output = '''
MLjLMLLiLiQ
MLjLMLLiLQL
MLjLMLLiLQM
MLjLMLLiLQj
MLjLMLLiLQi
MLjLMLLiLQQ
MLjLMLLiMLL
MLjLMLLiMLM
MLjLMLLiMLj
MLjLMLLiMLi
MLjLMLLiMLQ
MLjLMLLiMML
MLjLMLLiMMM
MLjLMLLiMMj
MLjLMLLiMMi
MLjLMLLiMMQ
MLjLMLLiMjL
MLjLMLLiMjM
MLjLMLLiMjj
MLjLMLLiMji
MLjLMLLiMjQ
MLjLMLLiMiL
MLjLMLLiMiM
MLjLMLLiMij
MLjLMLLiMii
MLjLMLLiMiQ
MLjLMLLiMQL
'''

[[tests]]
input = '''
3 12
8
888
'''
output = '''
888
888
888
888
888
888
888
888
888
888
888
888
'''

[[tests]]
input = '''
11 22
9d2U
9U2Udd9U92d
'''
output = '''
9U2Udd9U922
9U2Udd9U92U
9U2Udd9U9U9
9U2Udd9U9Ud
9U2Udd9U9U2
9U2Udd9U9UU
9U2Udd9Ud99
9U2Udd9Ud9d
9U2Udd9Ud92
9U2Udd9Ud9U
9U2Udd9Udd9
9U2Udd9Uddd
9U2Udd9Udd2
9U2Udd9UddU
9U2Udd9Ud29
9U2Udd9Ud2d
9U2Udd9Ud22
9U2Udd9Ud2U
9U2Udd9UdU9
9U2Udd9UdUd
9U2Udd9UdU2
9U2Udd9UdUU
'''

[[tests]]
input = '''
3 16
xqjESTip3D
DiS
'''
output = '''
DiT
Dii
Dip
Di3
DiD
Dpx
Dpq
Dpj
DpE
DpS
DpT
Dpi
Dpp
Dp3
DpD
D3x
'''

[[tests]]
input = '''
8 16
rzU
UzrzzUzr
'''
output = '''
UzrzzUzz
UzrzzUzU
UzrzzUUr
UzrzzUUz
UzrzzUUU
UzrzUrrr
UzrzUrrz
UzrzUrrU
UzrzUrzr
UzrzUrzz
UzrzUrzU
UzrzUrUr
UzrzUrUz
UzrzUrUU
UzrzUzrr
UzrzUzrz
'''

[[tests]]
input = '''
20 24
ixGEq8p4X
EpqXi4Xp44q8pq8q8q8X
'''
output = '''
EpqXi4Xp44q8pq8q8qpi
EpqXi4Xp44q8pq8q8qpx
EpqXi4Xp44q8pq8q8qpG
EpqXi4Xp44q8pq8q8qpE
EpqXi4Xp44q8pq8q8qpq
EpqXi4Xp44q8pq8q8qp8
EpqXi4Xp44q8pq8q8qpp
EpqXi4Xp44q8pq8q8qp4
EpqXi4Xp44q8pq8q8qpX
EpqXi4Xp44q8pq8q8q4i
EpqXi4Xp44q8pq8q8q4x
EpqXi4Xp44q8pq8q8q4G
EpqXi4Xp44q8pq8q8q4E
EpqXi4Xp44q8pq8q8q4q
EpqXi4Xp44q8pq8q8q48
EpqXi4Xp44q8pq8q8q4p
EpqXi4Xp44q8pq8q8q44
EpqXi4Xp44q8pq8q8q4X
EpqXi4Xp44q8pq8q8qXi
EpqXi4Xp44q8pq8q8qXx
EpqXi4Xp44q8pq8q8qXG
EpqXi4Xp44q8pq8q8qXE
EpqXi4Xp44q8pq8q8qXq
EpqXi4Xp44q8pq8q8qX8
'''

[[tests]]
input = '''
3 3
tfpJwBZ
wtB
'''
output = '''
wtZ
wft
wff
'''

[[tests]]
input = '''
10 23
PcuV3w
Vw33wPcPVc
'''
output = '''
Vw33wPcPVu
Vw33wPcPVV
Vw33wPcPV3
Vw33wPcPVw
Vw33wPcP3P
Vw33wPcP3c
Vw33wPcP3u
Vw33wPcP3V
Vw33wPcP33
Vw33wPcP3w
Vw33wPcPwP
Vw33wPcPwc
Vw33wPcPwu
Vw33wPcPwV
Vw33wPcPw3
Vw33wPcPww
Vw33wPccPP
Vw33wPccPc
Vw33wPccPu
Vw33wPccPV
Vw33wPccP3
Vw33wPccPw
Vw33wPcccP
'''

[[tests]]
input = '''
20 11
8GWeuH
HeW8HWeuuGGeGWueHGW8
'''
output = '''
HeW8HWeuuGGeGWueHGWG
HeW8HWeuuGGeGWueHGWW
HeW8HWeuuGGeGWueHGWe
HeW8HWeuuGGeGWueHGWu
HeW8HWeuuGGeGWueHGWH
HeW8HWeuuGGeGWueHGe8
HeW8HWeuuGGeGWueHGeG
HeW8HWeuuGGeGWueHGeW
HeW8HWeuuGGeGWueHGee
HeW8HWeuuGGeGWueHGeu
HeW8HWeuuGGeGWueHGeH
'''

[[tests]]
input = '''
12 26
Aorz
ArAorzrArAAA
'''
output = '''
ArAorzrArAAo
ArAorzrArAAr
ArAorzrArAAz
ArAorzrArAoA
ArAorzrArAoo
ArAorzrArAor
ArAorzrArAoz
ArAorzrArArA
ArAorzrArAro
ArAorzrArArr
ArAorzrArArz
ArAorzrArAzA
ArAorzrArAzo
ArAorzrArAzr
ArAorzrArAzz
ArAorzrAroAA
ArAorzrAroAo
ArAorzrAroAr
ArAorzrAroAz
ArAorzrArooA
ArAorzrArooo
ArAorzrAroor
ArAorzrArooz
ArAorzrArorA
ArAorzrAroro
ArAorzrArorr
'''

[[tests]]
input = '''
18 7
TZLVBCs
sVTZVZCTLVZTBssBZV
'''
output = '''
sVTZVZCTLVZTBssBZB
sVTZVZCTLVZTBssBZC
sVTZVZCTLVZTBssBZs
sVTZVZCTLVZTBssBLT
sVTZVZCTLVZTBssBLZ
sVTZVZCTLVZTBssBLL
sVTZVZCTLVZTBssBLV
'''

[[tests]]
input = '''
5 1
T9hRn0
0RnhR
'''
output = '''
0Rnhn
'''

[[tests]]
input = '''
15 14
wY102TMbhm
bMb200YhM0Yw2b2
'''
output = '''
bMb200YhM0Yw2bT
bMb200YhM0Yw2bM
bMb200YhM0Yw2bb
bMb200YhM0Yw2bh
bMb200YhM0Yw2bm
bMb200YhM0Yw2hw
bMb200YhM0Yw2hY
bMb200YhM0Yw2h1
bMb200YhM0Yw2h0
bMb200YhM0Yw2h2
bMb200YhM0Yw2hT
bMb200YhM0Yw2hM
bMb200YhM0Yw2hb
bMb200YhM0Yw2hh
'''

[[tests]]
input = '''
17 30
7gx
7gx7xg7xx7xxxgxg7
'''
output = '''
7gx7xg7xx7xxxgxgg
7gx7xg7xx7xxxgxgx
7gx7xg7xx7xxxgxx7
7gx7xg7xx7xxxgxxg
7gx7xg7xx7xxxgxxx
7gx7xg7xx7xxxx777
7gx7xg7xx7xxxx77g
7gx7xg7xx7xxxx77x
7gx7xg7xx7xxxx7g7
7gx7xg7xx7xxxx7gg
7gx7xg7xx7xxxx7gx
7gx7xg7xx7xxxx7x7
7gx7xg7xx7xxxx7xg
7gx7xg7xx7xxxx7xx
7gx7xg7xx7xxxxg77
7gx7xg7xx7xxxxg7g
7gx7xg7xx7xxxxg7x
7gx7xg7xx7xxxxgg7
7gx7xg7xx7xxxxggg
7gx7xg7xx7xxxxggx
7gx7xg7xx7xxxxgx7
7gx7xg7xx7xxxxgxg
7gx7xg7xx7xxxxgxx
7gx7xg7xx7xxxxx77
7gx7xg7xx7xxxxx7g
7gx7xg7xx7xxxxx7x
7gx7xg7xx7xxxxxg7
7gx7xg7xx7xxxxxgg
7gx7xg7xx7xxxxxgx
7gx7xg7xx7xxxxxx7
'''

[[tests]]
input = '''
13 20
SURK
KSUURKUSKUSKR
'''
output = '''
KSUURKUSKUSKK
KSUURKUSKUUSS
KSUURKUSKUUSU
KSUURKUSKUUSR
KSUURKUSKUUSK
KSUURKUSKUUUS
KSUURKUSKUUUU
KSUURKUSKUUUR
KSUURKUSKUUUK
KSUURKUSKUURS
KSUURKUSKUURU
KSUURKUSKUURR
KSUURKUSKUURK
KSUURKUSKUUKS
KSUURKUSKUUKU
KSUURKUSKUUKR
KSUURKUSKUUKK
KSUURKUSKURSS
KSUURKUSKURSU
KSUURKUSKURSR
'''

[[tests]]
input = '''
8 10
I
IIIIIIII
'''
output = '''
IIIIIIII
IIIIIIII
IIIIIIII
IIIIIIII
IIIIIIII
IIIIIIII
IIIIIIII
IIIIIIII
IIIIIIII
IIIIIIII
'''

[[tests]]
input = '''
13 23
85
8855855858555
'''
output = '''
8855855855888
8855855855885
8855855855858
8855855855855
8855855855588
8855855855585
8855855855558
8855855855555
8855855588888
8855855588885
8855855588858
8855855588855
8855855588588
8855855588585
8855855588558
8855855588555
8855855585888
8855855585885
8855855585858
8855855585855
8855855585588
8855855585585
8855855585558
'''

[[tests]]
input = '''
15 13
SCJa7m
JmJamJaC7aaJSaa
'''
output = '''
JmJamJaC7aaJSa7
JmJamJaC7aaJSam
JmJamJaC7aaJS7S
JmJamJaC7aaJS7C
JmJamJaC7aaJS7J
JmJamJaC7aaJS7a
JmJamJaC7aaJS77
JmJamJaC7aaJS7m
JmJamJaC7aaJSmS
JmJamJaC7aaJSmC
JmJamJaC7aaJSmJ
JmJamJaC7aaJSma
JmJamJaC7aaJSm7
'''

[[tests]]
input = '''
5 9
od3Kw
KdKoK
'''
output = '''
KdKow
KdKdo
KdKdd
KdKd3
KdKdK
KdKdw
KdK3o
KdK3d
KdK33
'''

[[tests]]
input = '''
14 29
dOWMqu
uqddWWMuOOudOM
'''
output = '''
uqddWWMuOOudOq
uqddWWMuOOudOu
uqddWWMuOOudWd
uqddWWMuOOudWO
uqddWWMuOOudWW
uqddWWMuOOudWM
uqddWWMuOOudWq
uqddWWMuOOudWu
uqddWWMuOOudMd
uqddWWMuOOudMO
uqddWWMuOOudMW
uqddWWMuOOudMM
uqddWWMuOOudMq
uqddWWMuOOudMu
uqddWWMuOOudqd
uqddWWMuOOudqO
uqddWWMuOOudqW
uqddWWMuOOudqM
uqddWWMuOOudqq
uqddWWMuOOudqu
uqddWWMuOOudud
uqddWWMuOOuduO
uqddWWMuOOuduW
uqddWWMuOOuduM
uqddWWMuOOuduq
uqddWWMuOOuduu
uqddWWMuOOuOdd
uqddWWMuOOuOdO
uqddWWMuOOuOdW
'''

[[tests]]
input = '''
13 19
ORuIN
IIuOOONNIuORR
'''
output = '''
IIuOOONNIuORu
IIuOOONNIuORI
IIuOOONNIuORN
IIuOOONNIuOuO
IIuOOONNIuOuR
IIuOOONNIuOuu
IIuOOONNIuOuI
IIuOOONNIuOuN
IIuOOONNIuOIO
IIuOOONNIuOIR
IIuOOONNIuOIu
IIuOOONNIuOII
IIuOOONNIuOIN
IIuOOONNIuONO
IIuOOONNIuONR
IIuOOONNIuONu
IIuOOONNIuONI
IIuOOONNIuONN
IIuOOONNIuROO
'''

[[tests]]
input = '''
10 21
8e9O
9Oe899OOOe
'''
output = '''
9Oe899OOO9
9Oe899OOOO
9Oe89O8888
9Oe89O888e
9Oe89O8889
9Oe89O888O
9Oe89O88e8
9Oe89O88ee
9Oe89O88e9
9Oe89O88eO
9Oe89O8898
9Oe89O889e
9Oe89O8899
9Oe89O889O
9Oe89O88O8
9Oe89O88Oe
9Oe89O88O9
9Oe89O88OO
9Oe89O8e88
9Oe89O8e8e
9Oe89O8e89
'''

[[tests]]
input = '''
4 3
70VdLkU
0kL0
'''
output = '''
0kLV
0kLd
0kLL
'''

[[tests]]
input = '''
20 24
6CynZJ7gpc
n6JnZgppZ67ZnZZpZ76C
'''
output = '''
n6JnZgppZ67ZnZZpZ76y
n6JnZgppZ67ZnZZpZ76n
n6JnZgppZ67ZnZZpZ76Z
n6JnZgppZ67ZnZZpZ76J
n6JnZgppZ67ZnZZpZ767
n6JnZgppZ67ZnZZpZ76g
n6JnZgppZ67ZnZZpZ76p
n6JnZgppZ67ZnZZpZ76c
n6JnZgppZ67ZnZZpZ7C6
n6JnZgppZ67ZnZZpZ7CC
n6JnZgppZ67ZnZZpZ7Cy
n6JnZgppZ67ZnZZpZ7Cn
n6JnZgppZ67ZnZZpZ7CZ
n6JnZgppZ67ZnZZpZ7CJ
n6JnZgppZ67ZnZZpZ7C7
n6JnZgppZ67ZnZZpZ7Cg
n6JnZgppZ67ZnZZpZ7Cp
n6JnZgppZ67ZnZZpZ7Cc
n6JnZgppZ67ZnZZpZ7y6
n6JnZgppZ67ZnZZpZ7yC
n6JnZgppZ67ZnZZpZ7yy
n6JnZgppZ67ZnZZpZ7yn
n6JnZgppZ67ZnZZpZ7yZ
n6JnZgppZ67ZnZZpZ7yJ
'''

[[tests]]
input = '''
1 1
rXD3soIFNP
r
'''
output = '''
X
'''

[[tests]]
input = '''
14 19
sputD4
stsuD4ttpupttD
'''
output = '''
stsuD4ttpuptt4
stsuD4ttpuptDs
stsuD4ttpuptDp
stsuD4ttpuptDu
stsuD4ttpuptDt
stsuD4ttpuptDD
stsuD4ttpuptD4
stsuD4ttpupt4s
stsuD4ttpupt4p
stsuD4ttpupt4u
stsuD4ttpupt4t
stsuD4ttpupt4D
stsuD4ttpupt44
stsuD4ttpupDss
stsuD4ttpupDsp
stsuD4ttpupDsu
stsuD4ttpupDst
stsuD4ttpupDsD
stsuD4ttpupDs4
'''

[[tests]]
input = '''
14 5
tQV
QQVtQVQttVQQVt
'''
output = '''
QQVtQVQttVQQVQ
QQVtQVQttVQQVV
QQVtQVQttVQVtt
QQVtQVQttVQVtQ
QQVtQVQttVQVtV
'''

[[tests]]
input = '''
12 12
8
888888888888
'''
output = '''
888888888888
888888888888
888888888888
888888888888
888888888888
888888888888
888888888888
888888888888
888888888888
888888888888
888888888888
888888888888
'''
