[[tests]]
input = '''
8
'''
output = '''
2 3
'''

[[tests]]
input = '''
40
'''
output = '''
2 3
5 1
'''

[[tests]]
input = '''
55
'''
output = '''
5 1
11 1
'''

[[tests]]
input = '''
552
'''
output = '''
2 3
3 1
23 1
'''

[[tests]]
input = '''
169400
'''
output = '''
2 3
5 2
7 1
11 2
'''
