[[tests]]
input = '''
5
5000000
'''
output = '''
0
'''

[[tests]]
input = '''
5
5004000
'''
output = '''
4000
'''

[[tests]]
input = '''
3
123456
'''
output = '''
12456
'''

[[tests]]
input = '''
9
99999999991999999
'''
output = '''
1
'''

[[tests]]
input = '''
7
777
'''
output = '''
0
'''
