[[tests]]
input = '''
10
1
'''
output = '''
10
'''

[[tests]]
input = '''
20
1
'''
output = '''
16
'''

[[tests]]
input = '''
200
10
'''
output = '''
67
'''

[[tests]]
input = '''
500
30
'''
output = '''
122
'''

[[tests]]
input = '''
200
1
'''
output = '''
60
'''

[[tests]]
input = '''
500
100
'''
output = '''
185
'''
