[[tests]]
input = '''
6
3
'''
output = '''
2
0
2.00
'''

[[tests]]
input = '''
7
3
'''
output = '''
2
1
2.33
'''

[[tests]]
input = '''
5
2
'''
output = '''
2
1
2.50
'''

[[tests]]
input = '''
4
10
'''
output = '''
0
4
0.40
'''

[[tests]]
input = '''
1
1
'''
output = "1\n0\n1.00\n"

[[tests]]
input = '''
-1
1
'''
output = "-1\n0\n-1.00\n"

[[tests]]
input = '''
1
-1
'''
output = "-1\n0\n-1.00\n"

[[tests]]
input = '''
-1
-1
'''
output = "1\n0\n1.00\n"

[[tests]]
input = '''
7
-3
'''
output = "-2\n1\n-2.33\n"

[[tests]]
input = '''
-7
3
'''
output = "-2\n-1\n-2.33\n"

[[tests]]
input = '''
-7
-3
'''
output = "2\n-1\n2.33\n"

[[tests]]
input = '''
1000000
3
'''
output = "333333\n1\n333333.33\n"

[[tests]]
input = '''
-1000000
3
'''
output = "-333333\n-1\n-333333.33\n"

[[tests]]
input = '''
1
1000000
'''
output = "0\n1\n0.00\n"

[[tests]]
input = '''
-387237
-904883
'''
output = "0\n-387237\n0.43\n"

[[tests]]
input = '''
-80217
-496467
'''
output = "0\n-80217\n0.16\n"

[[tests]]
input = '''
-678530
-413204
'''
output = "1\n-265326\n1.64\n"

[[tests]]
input = '''
-818125
499372
'''
output = "-1\n-318753\n-1.64\n"

[[tests]]
input = '''
-549507
-349141
'''
output = "1\n-200366\n1.57\n"

[[tests]]
input = '''
640544
415402
'''
output = "1\n225142\n1.54\n"

[[tests]]
input = '''
487680
-541596
'''
output = "0\n487680\n-0.90\n"

[[tests]]
input = '''
-140894
-744624
'''
output = "0\n-140894\n0.19\n"

[[tests]]
input = '''
188550
566878
'''
output = "0\n188550\n0.33\n"

[[tests]]
input = '''
-20219
-941731
'''
output = "0\n-20219\n0.02\n"

[[tests]]
input = '''
-163497
-235387
'''
output = "0\n-163497\n0.69\n"

[[tests]]
input = '''
-529072
-502360
'''
output = "1\n-26712\n1.05\n"

[[tests]]
input = '''
-398884
-55357
'''
output = "7\n-11385\n7.21\n"

[[tests]]
input = '''
-874387
-595959
'''
output = "1\n-278428\n1.47\n"

[[tests]]
input = '''
-803630
159579
'''
output = "-5\n-5735\n-5.04\n"

[[tests]]
input = '''
721554
809021
'''
output = "0\n721554\n0.89\n"
