[[tests]]
input = '''
18
15
5
c
c
g
v
g
'''
output = '''
16
Cebolinha
'''

[[tests]]
input = '''
15
18
5
c
c
g
v
g
'''
output = '''
16
Chico Bento
'''

[[tests]]
input = '''
17
15
5
c
c
g
v
g
'''
output = '''
16
empate
'''

[[tests]]
input = '''
4
4
1
c
'''
output = '''
4
empate
'''

[[tests]]
input = '''
7
8
2
g
c
'''
output = '''
6
Chico Bento
'''

[[tests]]
input = '''
15
15
5
c
c
g
v
g
'''
output = '''
16
empate
'''

[[tests]]
input = '''
15
17
5
c
c
g
v
g
'''
output = '''
16
empate
'''

[[tests]]
input = '''
258
134
48
g
g
c
v
c
g
v
g
c
g
c
g
v
v
c
v
c
v
v
c
c
v
g
c
c
g
v
v
v
v
c
c
c
c
g
c
g
g
v
c
c
c
g
c
c
g
g
g
'''
output = '''
162
Cebolinha
'''

[[tests]]
input = '''
202
165
28
v
g
v
v
c
c
c
c
c
v
g
g
g
g
c
c
c
c
v
g
c
v
v
g
c
g
v
v
'''
output = '''
96
Cebolinha
'''

[[tests]]
input = '''
74
18
15
c
c
c
v
g
g
c
c
c
v
c
c
c
g
c
'''
output = '''
54
Chico Bento
'''

[[tests]]
input = '''
57
286
4
v
g
c
c
'''
output = '''
14
Chico Bento
'''

[[tests]]
input = '''
258
145
19
v
c
v
g
g
g
c
v
c
v
g
c
c
c
c
g
v
c
v
'''
output = '''
66
Cebolinha
'''

[[tests]]
input = '''
274
269
27
g
v
g
v
c
v
g
v
c
v
v
c
c
v
g
v
v
g
v
g
g
g
c
v
v
c
c
'''
output = '''
92
Cebolinha
'''

[[tests]]
input = '''
173
99
50
g
g
g
g
g
g
g
g
c
g
c
v
g
v
v
v
c
g
v
c
v
g
v
g
v
v
c
v
c
v
c
c
c
v
g
v
g
g
c
v
g
g
c
g
v
v
c
v
g
v
'''
output = '''
160
Chico Bento
'''

[[tests]]
input = '''
253
187
29
g
c
c
v
c
c
g
g
c
c
c
g
c
v
v
g
g
v
v
g
g
v
v
v
v
c
c
c
v
'''
output = '''
100
Cebolinha
'''

[[tests]]
input = '''
91
31
23
c
v
v
g
c
g
c
v
c
v
v
g
g
c
g
g
g
c
c
v
v
g
v
'''
output = '''
76
Chico Bento
'''

[[tests]]
input = '''
81
254
9
v
v
c
v
c
c
g
c
v
'''
output = '''
34
Chico Bento
'''

[[tests]]
input = '''
253
178
8
c
c
v
v
g
v
c
v
'''
output = '''
30
Cebolinha
'''

[[tests]]
input = '''
188
206
29
v
v
g
g
c
g
g
v
v
g
v
c
c
v
g
g
c
c
c
g
c
c
c
g
v
v
g
v
v
'''
output = '''
96
Chico Bento
'''

[[tests]]
input = '''
142
142
33
c
c
v
c
g
c
v
c
g
g
g
g
v
g
g
c
c
v
c
g
c
c
c
v
g
c
c
g
v
g
g
v
g
'''
output = '''
106
empate
'''

[[tests]]
input = '''
165
22
21
g
v
c
v
c
g
g
v
v
g
c
v
g
v
g
v
v
c
g
v
v
'''
output = '''
70
Cebolinha
'''

[[tests]]
input = '''
191
148
47
g
c
g
c
g
g
c
g
g
g
c
c
g
g
v
g
v
v
v
c
c
c
g
g
g
c
c
v
c
v
v
g
c
v
g
c
g
v
g
c
v
c
c
c
g
c
v
'''
output = '''
152
Cebolinha
'''

[[tests]]
input = '''
265
228
38
g
c
v
g
c
c
g
v
g
g
v
v
v
g
c
v
v
g
c
c
v
c
g
v
g
c
g
g
g
c
g
g
c
c
g
c
v
g
'''
output = '''
120
Cebolinha
'''

[[tests]]
input = '''
129
55
29
g
v
v
v
v
g
v
g
c
c
v
c
v
c
g
g
c
g
g
v
g
g
c
v
c
v
v
v
g
'''
output = '''
96
Chico Bento
'''

[[tests]]
input = '''
232
16
45
v
c
g
c
c
g
c
v
g
g
c
v
g
v
g
v
v
v
c
v
v
c
v
c
c
c
g
g
c
v
g
c
v
v
v
v
g
c
v
c
v
v
g
g
g
'''
output = '''
154
Chico Bento
'''

[[tests]]
input = '''
229
50
12
c
c
c
c
v
c
c
c
c
c
c
g
'''
output = '''
46
Cebolinha
'''

[[tests]]
input = '''
8
116
36
c
c
v
g
v
v
v
g
c
c
g
c
g
g
g
v
v
v
c
v
g
c
v
g
c
c
g
v
c
g
g
g
v
c
c
c
'''
output = '''
120
Cebolinha
'''

[[tests]]
input = '''
291
196
25
v
v
v
g
g
v
g
g
c
v
v
v
v
v
c
g
g
g
g
g
c
c
v
v
v
'''
output = '''
82
Cebolinha
'''

[[tests]]
input = '''
4
297
12
g
v
g
c
c
c
v
v
c
g
c
c
'''
output = '''
42
Chico Bento
'''

[[tests]]
input = '''
86
82
35
c
g
v
c
g
c
g
v
g
c
v
g
g
c
c
v
c
c
c
v
c
v
v
v
v
g
v
v
c
c
c
v
c
g
v
'''
output = '''
124
Chico Bento
'''
