[[tests]]
input = '''
aeiou  
arta euio auiaoauio riu pegasus
'''
output = '''
pessoa chefe chefe ultron pessoa
'''

[[tests]]
input = '''
aer
arta euio auiaoauio riu pegasus rea
'''
output = '''
ultron pessoa pessoa pessoa pessoa chefe
'''
