[[tests]]
input = '''
1
'''
output = '''
1
'''

[[tests]]
input = '''
6
'''
output = '''
8
'''

[[tests]]
input = '''
50
'''
output = '''
12586269025
'''

[[tests]]
input = '''
2
'''
output = '''
1
'''

[[tests]]
input = '''
9
'''
output = '''
34
'''

[[tests]]
input = '''
17
'''
output = '''
1597
'''

[[tests]]
input = '''
25
'''
output = '''
75025
'''

[[tests]]
input = '''
33
'''
output = '''
3524578
'''

[[tests]]
input = '''
41
'''
output = '''
165580141
'''

[[tests]]
input = '''
49
'''
output = '''
7778742049
'''

[[tests]]
input = '''
24
'''
output = '''
46368
'''

[[tests]]
input = '''
34
'''
output = '''
5702887
'''

[[tests]]
input = '''
8
'''
output = '''
21
'''

[[tests]]
input = '''
29
'''
output = '''
514229
'''

[[tests]]
input = '''
19
'''
output = '''
4181
'''

[[tests]]
input = '''
3
'''
output = '''
2
'''

[[tests]]
input = '''
32
'''
output = '''
2178309
'''

[[tests]]
input = '''
28
'''
output = '''
317811
'''

[[tests]]
input = '''
22
'''
output = '''
17711
'''

[[tests]]
input = '''
16
'''
output = '''
987
'''

[[tests]]
input = '''
12
'''
output = '''
144
'''

[[tests]]
input = '''
14
'''
output = '''
377
'''

[[tests]]
input = '''
20
'''
output = '''
6765
'''

[[tests]]
input = '''
10
'''
output = '''
55
'''

[[tests]]
input = '''
5
'''
output = '''
5
'''

[[tests]]
input = '''
42
'''
output = '''
267914296
'''

[[tests]]
input = '''
37
'''
output = '''
24157817
'''

[[tests]]
input = '''
35
'''
output = '''
9227465
'''

[[tests]]
input = '''
30
'''
output = '''
832040
'''

[[tests]]
input = '''
39
'''
output = '''
63245986
'''

[[tests]]
input = '''
0
'''
output = '''
1
'''
