[[tests]]
input = '''
4
9
'''
output = '''
9
'''

[[tests]]
input = '''
56
7
'''
output = '''
56
'''

[[tests]]
input = '''
46
-789
'''
output = '''
46
'''

[[tests]]
input = '''
-45
-125
'''
output = '''
-45
'''

[[tests]]
input = '''
-458
-12
'''
output = '''
-12
'''

[[tests]]
input = '''
458
12
'''
output = '''
458
'''

[[tests]]
input = '''
458
458
'''
output = '''
458
'''

[[tests]]
input = '''
0
1
'''
output = '''
1
'''

[[tests]]
input = '''
-458
-458
'''
output = '''
-458
'''

[[tests]]
input = '''
0
0
'''
output = '''
0
'''

[[tests]]
input = '''
-1
1
'''
output = '''
1
'''

[[tests]]
input = '''
1
-1
'''
output = '''
1
'''

[[tests]]
input = '''
-1000000000
-999999999
'''
output = '''
-999999999
'''

[[tests]]
input = '''
-1000000000
1000000000
'''
output = '''
1000000000
'''

[[tests]]
input = '''
1000000000
-1000000000
'''
output = '''
1000000000
'''

[[tests]]
input = '''
999999999
1000000000
'''
output = '''
1000000000
'''

[[tests]]
input = '''
-42
-42
'''
output = '''
-42
'''

[[tests]]
input = '''
-228535
-575477
'''
output = '''
-228535
'''

[[tests]]
input = '''
876010
-962271
'''
output = '''
876010
'''

[[tests]]
input = '''
646665
214924
'''
output = '''
646665
'''

[[tests]]
input = '''
215988
722115
'''
output = '''
722115
'''

[[tests]]
input = '''
514495
46696
'''
output = '''
514495
'''

[[tests]]
input = '''
632825
-630436
'''
output = '''
632825
'''

[[tests]]
input = '''
581620
466738
'''
output = '''
581620
'''

[[tests]]
input = '''
-690302
722617
'''
output = '''
722617
'''

[[tests]]
input = '''
424515
455722
'''
output = '''
455722
'''

[[tests]]
input = '''
879949
145348
'''
output = '''
879949
'''

[[tests]]
input = '''
896630
-566572
'''
output = '''
896630
'''

[[tests]]
input = '''
392423
-771595
'''
output = '''
392423
'''

[[tests]]
input = '''
-262233
-793193
'''
output = '''
-262233
'''
