[[tests]]
input = '''
3
1
1
1
'''
output = '''
1
'''

[[tests]]
input = '''
10
4
4
4
'''
output = '''
2
'''

[[tests]]
input = '''
2
4
2
3
'''
output = '''
5
'''

[[tests]]
input = '''
4
1
2
0
'''
output = '''
1
'''

[[tests]]
input = '''
20
80
20
30
'''
output = '''
7
'''

[[tests]]
input = '''
100
5
66
27
'''
output = '''
1
'''

[[tests]]
input = '''
7
20
13
16
'''
output = '''
7
'''

[[tests]]
input = '''
2
15
13
19
'''
output = '''
24
'''
