[[tests]]
input = '''
3
1
1
1
'''
output = '''
1
'''

[[tests]]
input = '''
10
4
4
4
'''
output = '''
2
'''

[[tests]]
input = '''
2
4
2
3
'''
output = '''
5
'''

[[tests]]
input = '''
4
1
2
0
'''
output = '''
1
'''

[[tests]]
input = '''
20
80
20
30
'''
output = '''
7
'''

[[tests]]
input = '''
100
5
66
27
'''
output = '''
1
'''

[[tests]]
input = '''
7
20
13
16
'''
output = '''
7
'''

[[tests]]
input = '''
2
15
13
19
'''
output = '''
24
'''

[[tests]]
input = '''
1
0
0
1
'''
output = '''
1
'''

[[tests]]
input = '''
3
2
2
1
'''
output = '''
2
'''

[[tests]]
input = '''
3
2
1
1
'''
output = '''
2
'''

[[tests]]
input = '''
3
2
2
2
'''
output = '''
2
'''

[[tests]]
input = '''
3
2
2
3
'''
output = '''
3
'''

[[tests]]
input = '''
100
30
30
40
'''
output = '''
1
'''

[[tests]]
input = '''
100
34
34
33
'''
output = '''
2
'''

[[tests]]
input = '''
2
300
300
400
'''
output = '''
500
'''

[[tests]]
input = '''
70
225
573
341
'''
output = '''
17
'''

[[tests]]
input = '''
53
38
751
812
'''
output = '''
31
'''

[[tests]]
input = '''
67
605
866
268
'''
output = '''
26
'''

[[tests]]
input = '''
82
276
126
347
'''
output = '''
10
'''

[[tests]]
input = '''
37
422
145
674
'''
output = '''
34
'''

[[tests]]
input = '''
19
164
84
25
'''
output = '''
15
'''

[[tests]]
input = '''
37
144
689
358
'''
output = '''
33
'''

[[tests]]
input = '''
95
451
552
426
'''
output = '''
16
'''

[[tests]]
input = '''
42
93
1000
56
'''
output = '''
28
'''

[[tests]]
input = '''
62
345
402
900
'''
output = '''
27
'''

[[tests]]
input = '''
100
506
188
905
'''
output = '''
16
'''

[[tests]]
input = '''
79
246
310
702
'''
output = '''
16
'''

[[tests]]
input = '''
49
568
621
666
'''
output = '''
38
'''

[[tests]]
input = '''
20
649
191
5
'''
output = '''
43
'''
