[[tests]]
input = '''
4
5
'''
output = '''
5
'''

[[tests]]
input = '''
5
4
'''
output = '''
5
'''

[[tests]]
input = '''
12
12
'''
output = '''
12
'''

[[tests]]
input = '''
-5
0
'''
output = '''
0
'''
