[[tests]]
input = '''
4 14 7 -1
'''
output = '''
S
'''

[[tests]]
input = '''
4 14 7 1
'''
output = '''
N
'''

[[tests]]
input = '''
15 9 8 -1
'''
output = '''
S
'''

[[tests]]
input = '''
0 14 15 -1
'''
output = '''
N
'''

[[tests]]
input = '''
8 12 11 -1
'''
output = '''
S
'''

[[tests]]
input = '''
12 6 13 -1
'''
output = '''
S
'''

[[tests]]
input = '''
10 6 13 -1
'''
output = '''
S
'''

[[tests]]
input = '''
15 3 13 1
'''
output = '''
S
'''

[[tests]]
input = '''
0 11 14 1
'''
output = '''
S
'''

[[tests]]
input = '''
2 4 13 1
'''
output = '''
S
'''
