[[tests]]
input = '''
123
5
'''
output = '''
321
'''

[[tests]]
input = '''
3215
1
'''
output = '''
3251
'''

[[tests]]
input = '''
4567
6
'''
output = '''
5467
'''

[[tests]]
input = '''
123456
8
'''
output = '''
124536
'''

[[tests]]
input = '''
7651
2
'''
output = '''
7651
'''

[[tests]]
input = '''
15578
3
'''
output = '''
15785
'''

[[tests]]
input = '''
321
8
'''
output = '''
321
'''

[[tests]]
input = '''
12345678
8
'''
output = '''
12346758
'''

[[tests]]
input = '''
0123456789
10
'''
output = '''
0123457968
'''

[[tests]]
input = '''
9081726354
5
'''
output = '''
9081732456
'''

[[tests]]
input = '''
6677
2
'''
output = '''
6776
'''

[[tests]]
input = '''
243909549
187
'''
output = '''
245099394
'''

[[tests]]
input = '''
409
13
'''
output = '''
940
'''

[[tests]]
input = '''
760
1
'''
output = '''
760
'''

[[tests]]
input = '''
935
140
'''
output = '''
953
'''

[[tests]]
input = '''
6898
166
'''
output = '''
9886
'''

[[tests]]
input = '''
4047
138
'''
output = '''
7440
'''

[[tests]]
input = '''
600358
82
'''
output = '''
806503
'''

[[tests]]
input = '''
568
99
'''
output = '''
865
'''

[[tests]]
input = '''
90339
54
'''
output = '''
99330
'''

[[tests]]
input = '''
91
111
'''
output = '''
91
'''

[[tests]]
input = '''
7120299164
36
'''
output = '''
7120469192
'''

[[tests]]
input = '''
2674606702
61
'''
output = '''
2674726600
'''

[[tests]]
input = '''
39
130
'''
output = '''
93
'''

[[tests]]
input = '''
3195
156
'''
output = '''
9531
'''

[[tests]]
input = '''
225842396
151
'''
output = '''
225963428
'''

[[tests]]
input = '''
2211
138
'''
output = '''
2211
'''

[[tests]]
input = '''
7
198
'''
output = '''
7
'''

[[tests]]
input = '''
86373238
176
'''
output = '''
87836332
'''

[[tests]]
input = '''
6
168
'''
output = '''
6
'''
