[[tests]]
input = '''
0
0
0
'''
output = '''
you must connect to wifi
'''

[[tests]]
input = '''
0
1
1
'''
output = '''
you must connect to wifi
'''

[[tests]]
input = '''
0
0
1
'''
output = '''
you must connect to wifi
'''

[[tests]]
input = '''
1
0
1
'''
output = '''
you need to login first
'''

[[tests]]
input = '''
1
0
0
'''
output = '''
you need to login first
'''

[[tests]]
input = '''
1
1
0
'''
output = '''
you must to login as admin
'''

[[tests]]
input = '''
1
1
1
'''
output = '''
done
'''
