[[tests]]
input = '''
1
16
'''
output = '''
1
2
zig
4
zag
zig
7
8
zig
zag
11
zig
13
14
zigzag
16
'''

[[tests]]
input = '''
25
35
'''
output = '''
zag
26
zig
28
29
zigzag
31
32
zig
34
zag
'''

[[tests]]
input = '''
-78
-72
'''
output = '''
zig
-77
-76
zigzag
-74
-73
zig
'''

[[tests]]
input = '''
49
76
'''
output = '''
49
zag
zig
52
53
zig
zag
56
zig
58
59
zigzag
61
62
zig
64
zag
zig
67
68
zig
zag
71
zig
73
74
zigzag
76
'''

[[tests]]
input = '''
1
21
'''
output = '''
1
2
zig
4
zag
zig
7
8
zig
zag
11
zig
13
14
zigzag
16
17
zig
19
zag
zig
'''

[[tests]]
input = '''
-55
-36
'''
output = '''
zag
zig
-53
-52
zig
zag
-49
zig
-47
-46
zigzag
-44
-43
zig
-41
zag
zig
-38
-37
zig
'''

[[tests]]
input = '''
33
38
'''
output = '''
zig
34
zag
zig
37
38
'''

[[tests]]
input = '''
-16
-7
'''
output = '''
-16
zigzag
-14
-13
zig
-11
zag
zig
-8
-7
'''

[[tests]]
input = '''
-53
-26
'''
output = '''
-53
-52
zig
zag
-49
zig
-47
-46
zigzag
-44
-43
zig
-41
zag
zig
-38
-37
zig
zag
-34
zig
-32
-31
zigzag
-29
-28
zig
-26
'''

[[tests]]
input = '''
63
76
'''
output = '''
zig
64
zag
zig
67
68
zig
zag
71
zig
73
74
zigzag
76
'''

[[tests]]
input = '''
-86
-65
'''
output = '''
-86
zag
zig
-83
-82
zig
zag
-79
zig
-77
-76
zigzag
-74
-73
zig
-71
zag
zig
-68
-67
zig
zag
'''

[[tests]]
input = '''
85
115
'''
output = '''
zag
86
zig
88
89
zigzag
91
92
zig
94
zag
zig
97
98
zig
zag
101
zig
103
104
zigzag
106
107
zig
109
zag
zig
112
113
zig
zag
'''

[[tests]]
input = '''
54
67
'''
output = '''
zig
zag
56
zig
58
59
zigzag
61
62
zig
64
zag
zig
67
'''

[[tests]]
input = '''
-67
-67
'''
output = '''
-67
'''

[[tests]]
input = '''
20
33
'''
output = '''
zag
zig
22
23
zig
zag
26
zig
28
29
zigzag
31
32
zig
'''

[[tests]]
input = '''
92
102
'''
output = '''
92
zig
94
zag
zig
97
98
zig
zag
101
zig
'''

[[tests]]
input = '''
15
33
'''
output = '''
zigzag
16
17
zig
19
zag
zig
22
23
zig
zag
26
zig
28
29
zigzag
31
32
zig
'''

[[tests]]
input = '''
-42
-38
'''
output = '''
zig
-41
zag
zig
-38
'''

[[tests]]
input = '''
-12
-7
'''
output = '''
zig
-11
zag
zig
-8
-7
'''

[[tests]]
input = '''
10
35
'''
output = '''
zag
11
zig
13
14
zigzag
16
17
zig
19
zag
zig
22
23
zig
zag
26
zig
28
29
zigzag
31
32
zig
34
zag
'''

[[tests]]
input = '''
-71
-61
'''
output = '''
-71
zag
zig
-68
-67
zig
zag
-64
zig
-62
-61
'''

[[tests]]
input = '''
-40
-20
'''
output = '''
zag
zig
-38
-37
zig
zag
-34
zig
-32
-31
zigzag
-29
-28
zig
-26
zag
zig
-23
-22
zig
zag
'''

[[tests]]
input = '''
9
25
'''
output = '''
zig
zag
11
zig
13
14
zigzag
16
17
zig
19
zag
zig
22
23
zig
zag
'''

[[tests]]
input = '''
25
30
'''
output = '''
zag
26
zig
28
29
zigzag
'''

[[tests]]
input = '''
66
76
'''
output = '''
zig
67
68
zig
zag
71
zig
73
74
zigzag
76
'''

[[tests]]
input = '''
-72
-59
'''
output = '''
zig
-71
zag
zig
-68
-67
zig
zag
-64
zig
-62
-61
zigzag
-59
'''

[[tests]]
input = '''
-95
-91
'''
output = '''
zag
-94
zig
-92
-91
'''

[[tests]]
input = '''
-15
-1
'''
output = '''
zigzag
-14
-13
zig
-11
zag
zig
-8
-7
zig
zag
-4
zig
-2
-1
'''

[[tests]]
input = '''
-7
4
'''
output = '''
-7
zig
zag
-4
zig
-2
-1
zigzag
1
2
zig
4
'''

[[tests]]
input = '''
88
107
'''
output = '''
88
89
zigzag
91
92
zig
94
zag
zig
97
98
zig
zag
101
zig
103
104
zigzag
106
107
'''
