[[tests]]
input = '''
a porta amassou
'''
output = '''
a portaamassou
'''

[[tests]]
input = '''
carla almeida alencar
'''
output = '''
carlaalmeidaalencar
'''

[[tests]]
input = '''
a carla a ama
'''
output = '''
a carlaaama
'''

[[tests]]
input = '''
o orvalho ouviu uniformemente e eu uivei
'''
output = '''
oorvalhoouviuuniformementeeeuuivei
'''

[[tests]]
input = '''
cafe aroma
'''
output = '''
cafearoma
'''
