[[tests]]
input = '''
51
31
'''
output = '''
1 20
'''

[[tests]]
input = '''
398
50
'''
output = '''
7 48
'''

[[tests]]
input = '''
350
40
'''
output = '''
8 30
'''

[[tests]]
input = '''
587
460
'''
output = '''
1 127
'''

[[tests]]
input = '''
215
158
'''
output = '''
1 57
'''

[[tests]]
input = '''
760
360
'''
output = '''
2 40
'''

[[tests]]
input = '''
498
203
'''
output = '''
2 92
'''

[[tests]]
input = '''
61
25
'''
output = '''
2 11
'''

[[tests]]
input = '''
32
7
'''
output = '''
4 4
'''

[[tests]]
input = '''
873
254
'''
output = '''
3 111
'''

[[tests]]
input = '''
689
326
'''
output = '''
2 37
'''

[[tests]]
input = '''
939
155
'''
output = '''
6 9
'''

[[tests]]
input = '''
302
78
'''
output = '''
3 68
'''

[[tests]]
input = '''
584
318
'''
output = '''
1 266
'''

[[tests]]
input = '''
899
317
'''
output = '''
2 265
'''

[[tests]]
input = '''
1
1
'''
output = "1 0\n"

[[tests]]
input = '''
1
2
'''
output = "0 1\n"

[[tests]]
input = '''
999999
1
'''
output = "999999 0\n"

[[tests]]
input = '''
1000000
1000000
'''
output = "1 0\n"

[[tests]]
input = '''
1000000
3
'''
output = "333333 1\n"

[[tests]]
input = '''
249028
336182
'''
output = "0 249028\n"

[[tests]]
input = '''
377339
882144
'''
output = "0 377339\n"

[[tests]]
input = '''
554768
606577
'''
output = "0 554768\n"

[[tests]]
input = '''
749651
662728
'''
output = "1 86923\n"

[[tests]]
input = '''
410962
934024
'''
output = "0 410962\n"

[[tests]]
input = '''
835482
863966
'''
output = "0 835482\n"

[[tests]]
input = '''
130124
628278
'''
output = "0 130124\n"

[[tests]]
input = '''
157214
197361
'''
output = "0 157214\n"

[[tests]]
input = '''
796781
768782
'''
output = "1 27999\n"

[[tests]]
input = '''
81715
708609
'''
output = "0 81715\n"
