[[tests]]
input = '''
2
4
2000
1
4
2000
'''
output = '''
Mais recente
'''

[[tests]]
input = '''
2
3
1999
1
4
2000
'''
output = '''
Mais antiga
'''

[[tests]]
input = '''
1
4
2000
2
4
2000
'''
output = '''
Mais antiga
'''

[[tests]]
input = '''
1
4
2000
2
4
2001
'''
output = '''
Mais antiga
'''

[[tests]]
input = '''
1
5
2000
2
4
2000
'''
output = '''
Mais recente
'''

[[tests]]
input = '''
1
5
2000
1
5
2000
'''
output = '''
Iguais
'''
