[[tests]]
input = '''
121
'''
output = '''
1
'''

[[tests]]
input = '''
123
'''
output = '''
0
'''

[[tests]]
label = '03'
input = '''
122
'''
output = '''
0
'''

[[tests]]
label = '04'
input = '''
1
'''
output = '''
1
'''

[[tests]]
label = '05'
input = '''
11
'''
output = '''
1
'''

[[tests]]
label = '06'
input = '''
1235321
'''
output = '''
1
'''

[[tests]]
label = '07'
input = '''
0
'''
output = '''
1
'''

[[tests]]
label = '08'
input = '''
2220122
'''
output = '''
0
'''
