[[tests]]
input = '''
00
00
H
8
'''
output = '''
01 20
'''

[[tests]]
input = '''
00
10
A
74
'''
output = '''
11 50
'''

[[tests]]
input = '''
00
40
A
1
'''
output = '''
00 30
'''

[[tests]]
input = '''
00
10
A
2
'''
output = '''
11 50
'''

[[tests]]
input = '''
07
40
A
915
'''
output = '''
11 10
'''

[[tests]]
input = '''
05
10
H
492
'''
output = '''
03 10
'''

[[tests]]
input = '''
09
10
H
27
'''
output = '''
01 40
'''
