[[tests]]
input = '''
4
9
'''
output = '''
9
'''

[[tests]]
input = '''
56
7
'''
output = '''
56
'''

[[tests]]
input = '''
46
-789
'''
output = '''
46
'''

[[tests]]
input = '''
-45
-125
'''
output = '''
-45
'''

[[tests]]
input = '''
-458
-12
'''
output = '''
-12
'''

[[tests]]
input = '''
458
12
'''
output = '''
458
'''

[[tests]]
input = '''
458
458
'''
output = '''
458
'''

[[tests]]
input = '''
0
0
'''
output = '''
0
'''

[[tests]]
input = '''
-458
-458
'''
output = '''
-458
'''
