[[tests]]
input = '''
3
'''
output = '''
..3..
.3.3.
3.3.3
'''

[[tests]]
input = '''
2
'''
output = '''
.2.
2.2
'''

[[tests]]
input = '''
4
'''
output = '''
...4...
..4.4..
.4.4.4.
4.4.4.4
'''

[[tests]]
label = '04'
input = '''
1
'''
output = '''
1
'''

[[tests]]
label = '05'
input = '''
5
'''
output = '''
....5....
...5.5...
..5.5.5..
.5.5.5.5.
5.5.5.5.5
'''
