[[tests]]
label = '01'
input = '''
a
0
'''
output = '''
a
'''

[[tests]]
label = '02'
input = '''
b
3
'''
output = '''
e
'''

[[tests]]
label = '03'
input = '''
z
2
'''
output = '''
b
'''

[[tests]]
label = '04'
input = '''
f
-3
'''
output = '''
c
'''

[[tests]]
label = '05'
input = '''
b
-2
'''
output = '''
z
'''
