[[tests]]
input = '''
1
'''
output = '''
1
'''

[[tests]]
input = '''
2
'''
output = '''
1
'''

[[tests]]
input = '''
3
'''
output = '''
2
'''

[[tests]]
input = '''
4
'''
output = '''
3
'''

[[tests]]
input = '''
5
'''
output = '''
5
'''

[[tests]]
input = '''
6
'''
output = '''
8
'''

[[tests]]
input = '''
7
'''
output = '''
13
'''

[[tests]]
input = '''
8
'''
output = '''
21
'''

[[tests]]
input = '''
9
'''
output = '''
34
'''
