[[tests]]
input = '''
1
4
4
'''
output = '''
2
'''

[[tests]]
input = '''
1
5
4
'''
output = '''
0
'''

[[tests]]
input = '''
1
1
1
'''
output = '''
3
'''

[[tests]]
input = '''
1
3
3
'''
output = '''
2
'''

[[tests]]
input = '''
4
4
4
'''
output = '''
3
'''

[[tests]]
input = '''
1
5
1
'''
output = '''
2
'''

[[tests]]
input = '''
1
3
2
'''
output = '''
0
'''

[[tests]]
input = '''
6
5
4
'''
output = '''
0
'''
