[[tests]]
input = '''
01 00 00
03 00 00
'''
output = '''
02 00 00
'''

[[tests]]
input = '''
02 11 00
03 10 10
'''
output = '''
00 59 10
'''

[[tests]]
input = '''
04 10 00
03 10 10
'''
output = '''
23 00 10
'''

[[tests]]
input = '''
04 00 01
03 00 00
'''
output = '''
22 59 59
'''

[[tests]]
input = '''
0 0 0
1 1 1
'''
output = '''
01 01 01
'''

[[tests]]
input = '''
10 0 0
11 12 13
'''
output = '''
01 12 13
'''

[[tests]]
input = '''
04 05 00
03 05 00
'''
output = '''
23 00 00
'''

[[tests]]
input = '''
03 15 32
21 34 07
'''
output = '''
18 18 35
'''

[[tests]]
input = '''
21 15 32
06 34 09
'''
output = '''
09 18 37
'''
