[[tests]]
input = '''
123
5
'''
output = '''
321
'''

[[tests]]
input = '''
3215
1
'''
output = '''
3251
'''

[[tests]]
input = '''
4567
6
'''
output = '''
5467
'''

[[tests]]
input = '''
123456
8
'''
output = '''
124536
'''

[[tests]]
input = '''
7651
2
'''
output = '''
7651
'''

[[tests]]
input = '''
15578
3
'''
output = '''
15785
'''

[[tests]]
input = '''
321
8
'''
output = '''
321
'''

[[tests]]
input = '''
12345678
8
'''
output = '''
12346758
'''

[[tests]]
input = '''
0123456789
10
'''
output = '''
0123457968
'''

[[tests]]
input = '''
9081726354
5
'''
output = '''
9081732456
'''

[[tests]]
input = '''
6677
2
'''
output = '''
6776
'''
