[[tests]]
input = '''
amo o amor que me amou, oh amora amortecida
amo
'''
output = '''
5
'''

[[tests]]
input = '''
o rato ratificou o carate que rateamos no cerato.
rat
'''
output = '''
5
'''

[[tests]]
input = '''
lua de cristal que me faz sonhar menos
me
'''
output = '''
2
'''

[[tests]]
input = '''
marquei um x no seu umbigo de zumbak
um
'''
output = '''
3
'''

[[tests]]
input = '''
super golpe de kungfu
kungfu
'''
output = '''
1
'''
