[[tests]]
input = '''
5
'''
output = '''
1
'''

[[tests]]
input = '''
21
'''
output = '''
0
'''

[[tests]]
input = '''
2
'''
output = '''
1
'''

[[tests]]
label = '04'
input = '''
3
'''
output = '''
1
'''

[[tests]]
label = '05'
input = '''
4
'''
output = '''
0
'''

[[tests]]
label = '06'
input = '''
9
'''
output = '''
0
'''
